### ISSUE TITLE
Cannot convert OpenVINO IR to Blob format

### ISSUE THREAD

**Issue by GlowingHorse** [luxonis/depthai-experiments#101]
depthai-experiments/gen2-tf-image-classification/

I just tried to run the code of converting OpenVINO IR to Blob format in the colab file.
 `!/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/myriad_compile -m /content/flower/IR_models/FP32/flower.xml -ip U8 -VPU_NUMBER_OF_SHAVES 4 -VPU_NUMBER_OF_CMX_SLICES 4` 

But, it produces this:
`/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/myriad_compile: error while loading shared libraries: libinference_engine.so: cannot open shared object file: No such file or directory`.

Could you help see why this is happening?

**Comment by szabi-luxonis** [comment]
Before using openvino you have to initialize the environment variables with:
`source /opt/intel/openvino_2021/bin/setupvars.sh`
If that doesn't work then checkout [these](https://colab.research.google.com/drive/1oNxfvx5jOfcmk1Nx0qavjLN8KtWcLRn6#scrollTo=fk0YYXXdFzPj&line=12&uniqifier=1) 2 lines. I think this is a workaround for this issue.
```
#unknown bug - this is just a patch
!cp /opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbb.so /usr/lib/x86_64-linux-gnu/libtbb.so
!cp /opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 /usr/lib/x86_64-linux-gnu/libtbb.so.2
!ldconfig
```
@GlowingHorse

**Comment by raymondlo84** [comment]
Hi all, I have patched the file, as it seems there was an error. Please double-check and leave a message if it's still an issue. 

https://colab.research.google.com/drive/1oNxfvx5jOfcmk1Nx0qavjLN8KtWcLRn6?usp=sharing

**Comment by Luxonis-Brandon** [comment]
Thanks @raymondlo84 !
