### ISSUE TITLE
Decreased person detection FPS in Gen2 as compared to Gen1.

### ISSUE THREAD

**Issue by dhruvsheth-ai** [luxonis/depthai-experiments#120]
Recently, I tried to script a gen2 version of social distancing using `26_1_spatial_mobilenet.py` as reference to implement https://github.com/luxonis/depthai-experiments/pull/116#issuecomment-830640956. However, using `person-detection-retail-0013 OpenVINO v2021.3 model, 7 shaves` gives a 10FPS inference. 
Recent gen2-people-tracker example notices a 5FPS performance.

Comparing this to Gen1 social distancing which records 29FPS inference on RGB frame, but something similar as well (not recorded) on NN frame. This is a noticable FPS drop, so was wondering if there is a workaround for this. The FPS was recorded for RGB input frame and not the NN frame in gen1 example, but the display output as a 29FPS display, although the bounding boxes record a less FPS.

**Comment by Luxonis-Brandon** [comment]
Ah, got it.  So I think the difference is whether it is desirable to have synchronous or asynchronous.  So are you thinking asynchronous (show the preview at 30FPS, NN at lower rate) is better than synchronous (where the preview and the NN are at the same FPS)?

Thanks,
Brandon

**Comment by Luxonis-Brandon** [comment]
Thank you!
