### ISSUE TITLE
Using different model in pedestrian re-identification causes image size error

### ISSUE THREAD

**Issue by viyer-research** [luxonis/depthai-experiments#133]
![image](https://user-images.githubusercontent.com/8236526/119243949-15e43100-bb31-11eb-9712-85e3b68a7cef.png)

I converted using the blob converter and choose the right version 2020.1 but I still get an error, so how can I reshape my inputs from 544x320->672x383?
![image](https://user-images.githubusercontent.com/8236526/119243965-58a60900-bb31-11eb-946f-7a258bc824b1.png)

**Comment by dhruvsheth-ai** [comment]
Could you try changing - 
https://github.com/luxonis/depthai-experiments/blob/f6e909b5235241b875481cdcd78ca9b3333dc3fa/gen2-pedestrian-reidentification/main.py#L54

From 544x320->672x384 and give it a shot again?
Thanks.

**Comment by viyer-research** [comment]
It works now so I got further as the re-id algorithm uses two models one
for detection and another for re0id using cosine metric. The detector seems
to be swappable but the re-id blobs only work with pedestrians as I tried
vehicle-reid-001.blob. I got an error
    with dai.Device(pipeline) as device:
RuntimeError: Pipeline - 'NeuralNetwork' node with id: 5, isn't compatible
with forced OpenVINO version

Is there any way to make the re-id model compatible with the existing
network as vehicle-detection-adas-0002.blob works? Looking at the network
naming my blind guess would be if I can get vehicle-reid-0002 instead of
-0001. The model converted I am using is shown below.

[image: image.png]

Thanks,
Vasanth

**Comment by Erol444** [comment]
Hello @viyer-research, it's possible but you have to compile all models with the same openVino version. And you can specify the openVino version with `pipeline.setOpenVINOVersion(depthai.OpenVINO.Version.VERSION_2021_3)` (for openVino 2021.3)

**Comment by viyer-research** [comment]
Hi,

Thanks, I made it further to convert ALL models to 2020_4 but I am getting
this error:

[14442C1051AFC3D200] [176.371] [NeuralNetwork(5)] [warning] Number of
inference threads assigned for network is 1, assigning 2 will likely yield
in better performance
[14442C1051AFC3D200] [176.371] [NeuralNetwork(5)] [warning] Network
compiled for 4 shaves, maximum available 16, compiling for 8 shaves likely
will yield in better performance
[14442C1051AFC3D200] [176.371] [DetectionNetwork(0)] [warning] Network
compiled for 4 shaves, maximum available 16, compiling for 8 shaves likely
will yield in better performance
[14442C1051AFC3D200] [176.380] [NeuralNetwork(5)] [warning] The issued
warnings are orientative, based on optimal settings for a single network,
if multiple networks are running in parallel the optimal settings may vary
[14442C1051AFC3D200] [176.380] [DetectionNetwork(0)] [warning] The issued
warnings are orientative, based on optimal settings for a single network,
if multiple networks are running in parallel the optimal settings may vary
[14442C1051AFC3D200] [176.842] [NeuralNetwork(5)] [error] Input tensor
'input' (0) exceeds available data range. Data size (13824B), tensor offset
(0), size (129792B) - skipping inferenc
-------------------------
My modified code for version consistency is (as my libraries/header don't
have 2021_3, so I am using 2020_4 and converted accordingly

pipeline.setOpenVINOVersion(version = dai.OpenVINO.Version.VERSION_2020_4)

detection_nn.setBlobPath(str(Path("E:/OpenVINO-Re-ID/vehicle-detection-adas-0002-2020-4.blob").resolve().absolute()))
 #Works! with sie (672, 384)

reid_nn.setBlobPath(str(Path("E:/OpenVINO-Re-ID/vehicle-reid-0001-2020-4.blob").resolve().absolute()))
 # Vehicle RE-IDOn Sun, May 23, 2021 at 1:38 PM Erik
***@***.***> wrote:


Thanks,
Vasanth

**Comment by Erol444** [comment]
```[14442C1051AFC3D200] [176.842] [NeuralNetwork(5)] [error] Input tensor
'input' (0) exceeds available data range. Data size (13824B), tensor offset
(0), size (129792B) - skipping inference
```
could you share the whole script and what you are trying to accomplish? This happens because wrong data size is sent to the NN node.

**Comment by viyer-research** [comment]
Sorry for the delay as I was unable to attach the files. So I am sharing my private folder (MyCLoud) for the scripts and the models.:

https://files.mycloud.com/home.php?brand=webfiles&seuuid=c14a33e625bccd510818bb235288a3fb&name=DepthAI

The model blobs and the above python script can be downloaded from my private shared folder (depthai):

Let me know how to upgrade my Windows depthAi version from 2020.4 to 2021.3. 
Thanks,
Vasanth

P.S. 
----------------------------
import argparse
import time
import queue
import signal
import threading
from pathlib import Path

import cv2
import depthai as dai
print('depthai module: ', dai.__file__)
import numpy as np
from imutils.video import FPS

parser = argparse.ArgumentParser()
parser.add_argument('-nd', '--no-debug', action="store_true", help="Prevent debug output")
parser.add_argument('-cam', '--camera', action="store_true", help="Use DepthAI 4K RGB camera for inference (conflicts with -vid)")
parser.add_argument('-vid', '--video', type=str, help="Path to video file to be used for inference (conflicts with -cam)")
parser.add_argument('-w', '--width', default=1280, type=int, help="Visualization width. Height is calculated automatically from aspect ratio")
parser.add_argument('-lq', '--lowquality', action="store_true", help="Low quality visualization - uses resized frames")
args = parser.parse_args()

if not args.camera and not args.video:
    raise RuntimeError("No source selected. Please use either \"-cam\" to use RGB camera as a source or \"-vid <path>\" to run on video")

debug = not args.no_debug
camera = not args.video
hq = not args.lowquality

if args.camera and args.video:
    raise ValueError("Incorrect command line parameters! \"-cam\" cannot be used with \"-vid\"!")
elif args.camera is False and args.video is None:
    raise ValueError("Missing inference source! Either use \"-cam\" to run on DepthAI camera or \"-vid <path>\" to run on video file")


def cos_dist(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def frame_norm(frame, bbox):
    return (np.clip(np.array(bbox), 0, 1) * np.array([*frame.shape[:2], *frame.shape[:2]])[::-1]).astype(int)

def to_planar(arr: np.ndarray, shape: tuple) -> np.ndarray:
    resized = cv2.resize(arr, shape)
    return resized.transpose(2,0,1)

def create_pipeline():
    print("Creating pipeline...")
    pipeline = dai.Pipeline()
    #pipeline.setOpenVINOVersion(version = dai.OpenVINO.Version.VERSION_2020_1)
    pipeline.setOpenVINOVersion(version = dai.OpenVINO.Version.VERSION_2020_4)

    if camera:
        # ColorCamera
        print("Creating Color Camera...")
        cam = pipeline.createColorCamera()
        #cam.setPreviewSize(544, 320)
        cam.setPreviewSize(672, 384)
        cam.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
        cam.setInterleaved(False)
        cam.setBoardSocket(dai.CameraBoardSocket.RGB)
        cam_xout = pipeline.createXLinkOut()
        cam_xout.setStreamName("cam_out")
        # Link video output to host for higher resolution
        if hq:
            cam.video.link(cam_xout.input)
        else:
            cam.preview.link(cam_xout.input)

    # NeuralNetwork
    print("Creating Person Detection Neural Network...")
    detection_nn = pipeline.createMobileNetDetectionNetwork()
    #detection_nn.setBlobPath(str(Path("models/person-detection-retail-0013_openvino_2020.1_4shave.blob").resolve().absolute()))
    #detection_nn.setBlobPath(str(Path("C:/Vasanth/OAK-AI/depthai-experiments/gen2-pedestrian-reidentification/models/person-detection-retail-0013_openvino_2020.1_4shave.blob").resolve().absolute())) # Works with (544, 320))
    #detection_nn.setBlobPath(str(Path("E:/OpenVINO-Re-ID/vehicle-detection-adas-0002.blob").resolve().absolute()))  #Works! with sie (672, 384)
    detection_nn.setBlobPath(str(Path("E:/OpenVINO-Re-ID/vehicle-detection-adas-0002-2020-4.blob").resolve().absolute()))  #Works! with sie (672, 384)
    # Confidence
    detection_nn.setConfidenceThreshold(0.7)
    # Increase threads for detection
    detection_nn.setNumInferenceThreads(2)
    # Specify that network takes latest arriving frame in non-blocking manner
    detection_nn.input.setQueueSize(1)
    detection_nn.input.setBlocking(False)

    detection_nn_xout = pipeline.createXLinkOut()
    detection_nn_xout.setStreamName("detection_nn")

    detection_nn_passthrough = pipeline.createXLinkOut()
    detection_nn_passthrough.setStreamName("detection_passthrough")
    detection_nn_passthrough.setMetadataOnly(True)

    if camera:
        print('linked cam.preview to detection_nn.input')
        cam.preview.link(detection_nn.input)
    else:
        detection_in = pipeline.createXLinkIn()
        detection_in.setStreamName("detection_in")
        detection_in.out.link(detection_nn.input)

    detection_nn.out.link(detection_nn_xout.input)
    detection_nn.passthrough.link(detection_nn_passthrough.input)


    # NeuralNetwork
    print("Creating Person Reidentification Neural Network...")
    reid_in = pipeline.createXLinkIn()
    reid_in.setStreamName("reid_in")
    reid_nn = pipeline.createNeuralNetwork()
    #reid_nn.setBlobPath(str(Path("models/person-reidentification-retail-0031_openvino_2020.1_4shave.blob").resolve().absolute()))
    #reid_nn.setBlobPath(str(Path("C:/Vasanth/OAK-AI/depthai-experiments/gen2-pedestrian-reidentification/models/person-reidentification-retail-0031_openvino_2020.1_4shave.blob").resolve().absolute())) # Works!
    #reid_nn.setBlobPath(str(Path("C:/Vasanth/OAK-AI/depthai-experiments/gen2-pedestrian-reidentification/models/person-reidentification-retail-0031_openvino_2020.1_4shave.blob").resolve().absolute()))
    reid_nn.setBlobPath(str(Path("E:/OpenVINO-Re-ID/vehicle-reid-0001-2020-4.blob").resolve().absolute()))  # Vehicle RE-ID

    #reid_nn.setBlobPath(str(Path("E:/OpenVINO-Re-ID/vehicle-license-plate-detection-barrier-0123.blob").resolve().absolute()))  # Vehicle RE-ID

    # Decrease threads for reidentification
    reid_nn.setNumInferenceThreads(1)
    
    reid_nn_xout = pipeline.createXLinkOut()
    reid_nn_xout.setStreamName("reid_nn")
    reid_in.out.link(reid_nn.input)
    reid_nn.out.link(reid_nn_xout.input)

    print("Pipeline created.")
    return pipeline

class Main:
    def __init__(self):

        self.running = True
        self.FRAMERATE = 30.0

        if not camera:
            self.cap = cv2.VideoCapture(args.video)
            self.FRAMERATE = self.cap.get(cv2.CAP_PROP_FPS)

        print("framerate: ", self.FRAMERATE)

        self.frame_queue = queue.Queue()
        self.visualization_queue = queue.Queue(maxsize=4)

        self.nn_fps = 0

    def is_running(self):
        if self.running:
            if camera:
                return True
            else:
                return self.cap.isOpened()
        return False

    def inference_task(self):
        # Queues
        detection_passthrough = self.device.getOutputQueue("detection_passthrough")
        detection_nn = self.device.getOutputQueue("detection_nn")

        bboxes = []
        results = {}
        results_path = {}
        next_id = 0

        # Match up frames and detections
        try:
            prev_passthrough = detection_passthrough.getAll()[0]
            prev_inference = detection_nn.getAll()[0]
        except RuntimeError:
            pass

        fps = 0
        t_fps = time.time()
        while self.running:
            try:

                # Get current detection
                passthrough = detection_passthrough.getAll()[0]
                inference = detection_nn.getAll()[0]

                # Count NN fps
                fps = fps + 1

                # Combine all frames to current inference
                frames = []
                while True:

                    frm = self.frame_queue.get()
                    if camera and hq:
                        # Convert NV12 to BGR
                        yuv = frm.getData().reshape((frm.getHeight() * 3 // 2, frm.getWidth()))
                        cv_frame = cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR_NV12)                      
                    else:
                        # get the frames corresponding to inference
                        cv_frame = np.ascontiguousarray(frm.getData().reshape(3, frm.getHeight(), frm.getWidth()).transpose(1,2,0))

                    frames.append(cv_frame)

                    # Break out once all frames received for the current inference
                    if frm.getSequenceNum() >= prev_passthrough.getSequenceNum() - 1:
                        break

                infered_frame = frames[0]

                # Send bboxes to be infered upon
                for det in inference.detections:
                    raw_bbox = [det.xmin, det.ymin, det.xmax, det.ymax]
                    bbox = frame_norm(infered_frame, raw_bbox)
                    det_frame = infered_frame[bbox[1]:bbox[3], bbox[0]:bbox[2]]
                    nn_data = dai.NNData()
                    nn_data.setLayer("data", to_planar(det_frame, (48, 96)))
                    self.device.getInputQueue("reid_in").send(nn_data)

                 
                # Retrieve infered bboxes
                for det in inference.detections:

                    raw_bbox = [det.xmin, det.ymin, det.xmax, det.ymax]
                    bbox = frame_norm(infered_frame, raw_bbox)

                    reid_result = self.device.getOutputQueue("reid_nn").get().getFirstLayerFp16()

                    for person_id in results:
                        dist = cos_dist(reid_result, results[person_id])
                        if dist > 0.7:
                            result_id = person_id
                            results[person_id] = reid_result
                            break
                    else:
                        result_id = next_id
                        results[result_id] = reid_result
                        results_path[result_id] = []
                        next_id += 1

                    if debug:
                        for frame in frames:
                            cv2.rectangle(frame, (bbox[0], bbox[1]), (bbox[2], bbox[3]), (10, 245, 10), 2)
                            x = (bbox[0] + bbox[2]) // 2
                            y = (bbox[1] + bbox[3]) // 2
                            results_path[result_id].append([x, y])
                            cv2.putText(frame, str(result_id), (x, y), cv2.FONT_HERSHEY_TRIPLEX, 1.0, (255, 255, 255))
                            if len(results_path[result_id]) > 1:
                                cv2.polylines(frame, [np.array(results_path[result_id], dtype=np.int32)], False, (255, 0, 0), 2)
                    else:
                        print(f"Saw id: {result_id}")

                # Send of to visualization thread
                for frame in frames:
                    # put nn_fps
                    if debug:
                        cv2.putText(frame, 'NN FPS: '+str(self.nn_fps), (5,40), cv2.FONT_HERSHEY_DUPLEX, 1.0, (255,0,0), 2)

                    if self.visualization_queue.full():
                        self.visualization_queue.get_nowait()
                    self.visualization_queue.put(frame)
            

                # Move current to prev
                prev_passthrough = passthrough
                prev_inference = inference

                if time.time() - t_fps >= 1.0:
                    self.nn_fps = round(fps / (time.time() - t_fps), 2)
                    fps = 0
                    t_fps = time.time()

            except RuntimeError:
                continue



    def input_task(self):
        seq_num = 0
        while self.is_running():

            # Send images to next stage

            # if camera - receive frames from camera
            if camera:
                try:
                    frame = self.device.getOutputQueue('cam_out').get()
                    self.frame_queue.put(frame)
                except RuntimeError:
                    continue
            
            # else if video - send frames down to NN
            else:

                # Get frame from video capture
                read_correctly, vid_frame = self.cap.read()
                if not read_correctly:
                    break

                # Send to NN and to inference thread
                frame_nn = dai.ImgFrame()
                frame_nn.setSequenceNum(seq_num)
#                frame_nn.setWidth(544)
#                frame_nn.setHeight(320)
                frame_nn.setWidth(672)
                frame_nn.setHeight(384)
                frame_nn.setData(to_planar(vid_frame, (672, 384)))
#                frame_nn.setData(to_planar(vid_frame, (544, 320)))
                self.device.getInputQueue("detection_in").send(frame_nn)

                # if high quality, send original frames
                if hq:
                    frame_orig = dai.ImgFrame()
                    frame_orig.setSequenceNum(seq_num)
                    frame_orig.setWidth(vid_frame.shape[1])
                    frame_orig.setHeight(vid_frame.shape[0])
                    frame_orig.setData(to_planar(vid_frame, (vid_frame.shape[1], vid_frame.shape[0])))
                    self.frame_queue.put(frame_orig)
                # else send resized frames
                else: 
                    self.frame_queue.put(frame_nn)                

                seq_num = seq_num + 1

                # Sleep at video framerate
                time.sleep(1.0 / self.FRAMERATE)
        # Stop execution after input task doesn't have
        # any extra data anymore
        self.running = False


    def visualization_task(self):
        
        first = True
        while self.running:

            t1 = time.time()

            # Show frame if available
            if first or not self.visualization_queue.empty():
                frame = self.visualization_queue.get()
                aspect_ratio = frame.shape[1] / frame.shape[0]
                cv2.imshow("frame", cv2.resize(frame, (int(args.width),  int(args.width / aspect_ratio))))
                first = False

            # sleep if required
            to_sleep_ms = ((1.0 / self.FRAMERATE) - (time.time() - t1)) * 1000
            key = None
            if to_sleep_ms >= 1:
                key = cv2.waitKey(int(to_sleep_ms)) 
            else:
                key = cv2.waitKey(1)
            # Exit
            if key == ord('q'):
                self.running = False
                break

            

    def run(self):


        pipeline = create_pipeline()

        # Connect to the device
        with dai.Device(pipeline) as device:
            self.device = device

            print("Starting pipeline...")
            device.startPipeline()            

            threads = [
                threading.Thread(target=self.input_task),
                threading.Thread(target=self.inference_task), 
            ]
            for t in threads:
                t.start()

            # Visualization task should run in 'main' thread
            self.visualization_task()            

        # cleanup
        self.running = False
        if not camera:
            self.cap.release()
        for thread in threads:
            thread.join()


# Create the application
app = Main()

# Register a graceful CTRL+C shutdown
def signal_handler(sig, frame):
    app.running = False
signal.signal(signal.SIGINT, signal_handler)

# Run the application
app.run()
# Print latest NN FPS
print('FPS: ', app.nn_fps)
-------------------------------
Thanks,
Vasanth

**Comment by viyer-research** [comment]
After your suggestion, I was able to upgrade to
depthai.OpenVINO.Version.VERSION_2021_3  and compted all the models to have
the latest version. I am still getting the same error. The model works with
the re-id blob used in the pedestrian example so I check the size and found
the demo size is very small compared to the vehicle re-id model (8BM). Can
it be an OAK-D memory limitation as it seems to work in the OpenVino GPU
environment (not using the OAK-D.)

Thanks,
Vasanth

**Comment by Erol444** [comment]
@viyer-research I am guessing you were using video input when you got the error? And could you please share github gist instead of copying the code, since the visualization/formating is off here. Thanks:)

**Comment by viyer-research** [comment]
Hi ***@***.***

So I am sharing my private folder (MyCLoud) for the scripts and the
models.: Please click the link to download the file from the cloud folder
(I will try to put it into Github soon).

https://files.mycloud.com/home.php?brand=webfiles&seuuid=c14a33e625bccd510818bb235288a3fb&name=DepthAI

The model blobs and the above python script can be downloaded from my
private shared folder (depthai)

**Comment by viyer-research** [comment]
Hi ***@***.***

I have created a rep and all the test files including the models are
available to recreate the error.

https://github.com/viyer-research/fastreid.git

Let me know if you have any questions.

Thanks,

**Comment by Luxonis-Brandon** [comment]
Thanks!

**Comment by Erol444** [comment]
Hello @viyer-research , I checked the code, did you get the `vehicle-reid-0001` model working in a standalone (just that model)? It seems that's where the problem occurs. Looking at the https://docs.openvinotoolkit.org/latest/omz_models_model_vehicle_reid_0001.html, it seems like the input is `208x208` not `48x96`. And you could just use ImgFrame instead of NNData when feeding your image to the model.
Thanks, Erik

**Comment by viyer-research** [comment]
I changed the re-id sizes, and it now works. I may need one more pointer on
model conversion: is there a way to convert vehicle-reid-001.blob to
OpenVino vehicle-reid-001.xml vehicle-reid-001.bin as I need to test it
with C++ samples.

Thanks,

**Comment by Erol444** [comment]
That's wonderful to hear! So my suggestion would be to use local OpenVINO's [model_downloader](https://docs.openvinotoolkit.org/latest/omz_tools_downloader.html), download the model (I believe it will be in onnx format) and then use OpenVINO's [model optimizer](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html) to convert that into IR (xml/bin) :)

**Comment by viyer-research** [comment]
I have all the models set to 2020.4 and so far everything works fine. I
found some issue when using YOLO (all tiny and normal versions) which I
converted to blob using the site luxonis. When loading the models I get an
error:
Creating tracker
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual
Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual
Studio\Shared\Python37_64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "yolo-tiny-vehicle-blob-2020-4.py", line 241, in inference_task
    nn_data.setLayer("data", to_planar(det_frame, (208, 208)))
  File "yolo-tiny-vehicle-blob-2020-4.py", line 50, in to_planar
    resized = cv2.resize(arr, shape)
cv2.error: OpenCV(4.5.1)
C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\imgproc\src\resize.cpp:4051:
error: (-215:Assertion failed) !ssize.empty() in funct
ion 'cv::resize'

---
The code is attached for line 50 which is called from the function below
which is size 208x208 for vehicle-reid (works for mobilenetssd and
person-identification)

                    nn_data.setLayer("data", to_planar(det_frame, (208,
208)))
___________
Thanks,

**Comment by Erol444** [comment]
Hello @viyer-research ,
from the error, it looks like you are passing in an empty frame (variable `arr`) to the `cv2.resize()` function. You might want to check that out ;)

**Comment by viyer-research** [comment]
Hi,

I checked indeed the ndarray was 0 and it happens after the infered_frame
call. The first two detection was fine (see output below) in my test and
the third one has bbox but empty infered_frame? I don't see much of a
difference in the bbox range.

-----------------------------------------------
Creating tracker
bbox: [ 802  173 1247  689]
infered_frame-len: <class 'numpy.ndarray'> 688860
infered_frame: [[[236 225 209]
  [236 225 209]
  [236 225 209]
  ...
  [ 93 142 144]
  [101 150 152]
  [106 155 157]]

 [[236 225 209]
  [236 225 209]
  [236 225 209]
  ...
  [ 85 134 136]
  [ 84 133 135]
  [ 83 132 134]]

 [[236 225 209]
  [236 225 209]
  [236 225 209]
  ...
  [ 77 126 128]
  [ 66 115 117]
  [ 60 109 111]]

 ...

 [[ 64  76  88]
  [ 64  76  88]
  [ 64  76  88]
  ...
  [ 87  82  88]
  [ 87  82  88]
  [ 87  82  88]]

 [[ 64  76  88]
  [ 64  76  88]
  [ 64  76  88]
  ...
  [ 87  82  88]
  [ 87  82  88]
  [ 87  82  88]]

 [[ 64  76  88]
  [ 64  76  88]
  [ 64  76  88]
  ...
  [ 87  82  88]
  [ 87  82  88]
  [ 87  82  88]]]
bbox: [1275  500 1110  328]
infered_frame-len: <class 'numpy.ndarray'> 0

**Comment by Erol444** [comment]
Hello @viyer-research , we should move to discord (https://discord.gg/EPsZHkg9Nx) for better communication and we can help you resolve your issues there. Since we already resolved the original issue I will close it.
Thanks, Erik

**Comment by viyer-research** [comment]
Thanks, I posted the YOLO null issue just now.
