### ISSUE TITLE
gen2 palm detection - Neural network blob compile with uncompatible openvino version

### ISSUE THREAD

**Issue by magallardo** [luxonis/depthai-experiments#137]
Hello, 

I am running the gen2 palm detection sample and getting the following error.  Anything that needs to be done to fix this issue?  I am attaching the error in the console.

python3 main.py --cam
Loading pipeline...
Creating pipeline...
Creating Color Camera...
Creating models/palm_detection_openvino_2021.3_6shave.blob Neural Network...
linked cam.preview to model_nn.input
Pipeline created.
Starting pipeline...
[14442C100126C6D200] [372.086] [NeuralNetwork(2)] [error] Neural network blob compiled with uncompatible openvino version. Selected openvino version 2021.2. If you want to select an explicit openvino version use: setOpenVINOVersion while creating pipeline.
[14442C100126C6D200] [372.088] [NeuralNetwork(2)] [error] Neural network blob compiled with uncompatible openvino version. Selected openvino version 2021.2. If you want to select an explicit openvino version use: setOpenVINOVersion while creating pipeline.
^CTraceback (most recent call last):
  File "main.py", line 468, in <module>
    Main(camera=args.camera).run()
  File "main.py", line 252, in run
    self.run_camera()
  File "main.py", line 226, in run_camera
    in_rgb = self.preview.tryGet()

Thanks,
Marcelo

**Comment by Erol444** [comment]
Hello @magallardo ,
here is a solution: https://docs.luxonis.com/en/latest/pages/troubleshooting/#neural-network-blob-compiled-with-uncompatible-openvino-version
In a nutshell: you need to compile all NN models with the same openVino version and specify the version with the `pipeline.setOpenVINOVersion([VERSION])`.
Thanks, Erik

**Comment by magallardo** [comment]
@Erol444 I followed the instruction on the link you provided and based on the error message

Creating models/palm_detection_openvino_2021.3_6shave.blob Neural Network...

I set the OpenVINO version as indicated

self.pipeline.setOpenVINOVersion(depthai.OpenVINO.Version.VERSION_2021_3)

Then, I get the following error:

AttributeError: type object 'depthai.Version' has no attribute 'VERSION_2021_3'

Any other thing I need to change?  

Thanks,
Marcelo

**Comment by magallardo** [comment]
@Erol444 Please ignore previous message.  I fixed by forcing the install of the latest version of DepthAI libraries and that fixed the VERSION attribute issue. 

Thanks,
Marcelo

**Comment by Erol444** [comment]
Thanks for circling back and great to hear you got it to work! I will close this issue since it was resolved.
