### ISSUE TITLE
gen2-mjpeg-streaming not working

### ISSUE THREAD

**Issue by TannerGilbert** [luxonis/depthai-experiments#141]
The [gen2-mjpeg-streaming example](https://github.com/luxonis/depthai-experiments/tree/master/gen2-mjpeg-streaming) doesn't work on my Windows machine. If I use the library version specified inside the [requirements.txt](https://github.com/luxonis/depthai-experiments/blob/master/gen2-mjpeg-streaming/requirements.txt), I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 75, in <module>
    pipeline = dai.Pipeline()
TypeError: depthai.Pipeline: No constructor defined!
```

The specified depthai version inside the requirements.txt is `0.3.0.0+aeda4a9fdef6edc9f826b7dc354a123d1611a7c6` but as far as I know this isn't gen 2 yet so I tried to update the depthai version to `2.4.0.0`. After that, the TCP server works fine, but the HTTP Server crashes when I visit the page (localhost:8090).

If I remove [line 47](https://github.com/luxonis/depthai-experiments/blob/master/gen2-mjpeg-streaming/main.py#L47), the server stops crashing, but no image is displayed. Any help is highly appreciated.

**Comment by Luxonis-Brandon** [comment]
Sorry about the pain here, it looks like we failed to update the requirements.txt to use the right DepthAI version.

The engineer who wrote this is off today (he's moving) but will likely be back online on Monday to help.  I'm not immediately sure what is going wrong here, but beside the version issue (which is an oversight) I'm wondering if we just haven't tested this  on Windows - as usually Windows has a bit of a different set of needs, particularly when using external dependencies like this.

We'll circle back on Monday.  Sorry about the delay.  CC: @Erol444

**Comment by TannerGilbert** [comment]
@Luxonis-Brandon Thanks for the quick response. I'll try the script on my Linux machine tomorrow to see if it also crashes there or if it's only a Windows problem.

**Comment by TannerGilbert** [comment]
Just tried the script on Linux Mint, and it worked without any issues. Still couldn't get it to work on Windows, though.

**Comment by dhruvsheth-ai** [comment]
Thanks for the report @TannerGilbert. I've created a PR to update it to 2.4.0.0 - https://github.com/luxonis/depthai-experiments/pull/142/files

**Comment by Erol444** [comment]
Thanks again @dhruvsheth-ai  and sorry for the inconvenience @TannerGilbert!
