### ISSUE TITLE
Migrate RSTP streaming example to Gen2

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai-experiments#160]
We should migrate [rstp streaming example](https://github.com/luxonis/depthai-experiments/tree/master/rtsp-streaming) to Gen2.

Together with this migration, we can try to follow [this suggestion](https://github.com/luxonis/depthai/issues/294#issuecomment-881815401) in order to optimize CPU usage on the host

**Comment by eric-schleicher** [comment]
Question about how depthmaps fits into this pattern.   Is it considered a problem/challenge format wise to flow depthmaps through the device side encoding pipeline?  This lies right at the edge of my understanding and I'm very interesting in being able to stream depth over rtsp and to better understand the nuance of the formats as they pertain to HW encoding & streaming.


Can you comment on how these two links describe or factor in to the ability/quality to stream depthmaps using depthai HW encoding?

https://developers.google.com/depthmap-metadata/encoding
https://mpeg.chiariglione.org/standards/exploration/immersive-video/depth-map-formats-used-within-mpeg-3d-technologies

hoping to learn.  thanks.

**Comment by VanDavv** [comment]
Hi @eric-schleicher,
AFAIK, the videoencoder node supports only a limited number of frame formats and we cannot encode depth on device yet.
Regarding depthmaps support - I think @szabi-luxonis or @themarpe can elaborate but I don't think we'll be able to support custom formats in this node

**Comment by alex-luxonis** [comment]
The video encoder accelerator usually supports 8-bit NV12 color and 8-bit monochrome input, for all modes: H.264/H.265/JPEG.
So disparity can be encoded (but not in subpixel mode, where it goes up to 12-bit)

(The video encoder also should supports 10-bit input for H.26x, not JPEG, same formats as above, but this may not be configurable yet.)
