### ISSUE TITLE
Issue with 2 POE cameras running gen2-multiple-devices

### ISSUE THREAD

**Issue by CodingArcher** [luxonis/depthai-experiments#173]
Hi i am getting the following issue when only having two cammeras connected via POE

```
❯ python3 main.py
Conected to 192.168.1.5
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    device = stack.enter_context(dai.Device(pipeline, device_info))
RuntimeError: Failed to find device after booting, error message: X_LINK_DEVICE_NOT_FOUND
```

when i just check how many devices i have connected via ethernet for some reason i get ip douplications. Like two cameras gives me two IP back but doupled like this:

`❯ python3 main.py
Conected to 192.168.1.5
Conected to 192.168.1.5
Conected to 192.168.1.6
Conected to 192.168.1.6
`

**Comment by VanDavv** [comment]
@CodingArcher Hi,
I assumed you're using the `gen2-multiple-devices` experiment since it's the only place I see the ExitStack used. But then I saw that this error is at line 45 (whereas in this experiment it's in line 27), so you may be using some custom code here. I just gave it a try with 2 OAK-D-PoE and it all worked well. Maybe the custom pipeline you're trying to run is not working on the device?

**Comment by VanDavv** [comment]
Sorry @CodingArcher, just found out that this is a known issue and [an additional troubleshooting section](https://github.com/luxonis/depthai-docs-website/pull/242) regarding it should be available soon.

To quote:
>  We have seen that in some rare circumstances when your host computer is connected to the same LAN, it can happen that device discovery finds the same POE device twice, so it will print the IP address of that device 2 times. On some rare occasions this can lead to an error (we have seen this when using multiple devices) on initialization; `RuntimeError: Failed to find device after booting, error message: X_LINK_DEVICE_NOT_FOUND`.  We will try to fix this bug as soon as possible.
> **Workaround solution: disconnect from one of the interfaces; so disconnecting (from the) WiFi should resolve this issue.**

So I guess this matches your issue description perfectly. Could you check if you're connected both via Ethernet and WiFi?

**Comment by Erol444** [comment]
I believe we have resolved this issue in this [discuss thread](https://discuss.luxonis.com/d/274-runtimeerror-failed-t-after-booting-error-message-x-link-device-not-found/3).
