### ISSUE TITLE
[Idea] Chess pieces detection

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai-experiments#18]
Idea is to use DepthAI to recognize chess pieces on the chessboard, like in the gif below

![chess-detection-longer](https://user-images.githubusercontent.com/5244214/100866999-ce41ee00-3499-11eb-8c30-2d1b4aec07d3.gif)

Dataset and useful links can be found here - https://public.roboflow.com/object-detection/chess-full

**Comment by Erol444** [comment]
@VanDavv maybe not relevant anymore, since Roboflow has created this tutorial already:
https://blog.roboflow.com/deploy-luxonis-oak/

**Comment by VanDavv** [comment]
Yes, seems so, thanks for pointing out!
