### ISSUE TITLE
Memory leak issue with multiprocess queue

### ISSUE THREAD

**Issue by nickjrz** [luxonis/depthai-experiments#182]
https://github.com/luxonis/depthai-experiments/blob/39370819bcdfdb30e7ef3e21fc75391c41cac7b5/gen2-collecting-training-data/main.py#L237

There seems to be a memory leak bug on this multiprocess queue, I monitored my resources while running the code and my RAM kept exponentially increasing to the point where it would start to freeze my machine. This will cause issues especially on limited resources microcontrollers and SBCs. Maybe clearing the extracted_pair after putting it in the queue might fix the problem

**Comment by Luxonis-Brandon** [comment]
Thanks for the report and sorry for the error here.  I seem to recall @Erol444 having fixes something like this... maybe we forgot to push it?

**Comment by nickjrz** [comment]
No worries! I am testing this fix at the moment that creates an empty dictionary to store the extracted pairs before the while loop and inside the loop make sure we clear at the beginning of each iteration. So far the memory usage seems consistent 

`extracted_pair = {}
        while True:
            extracted_pair.clear()
            for queueName in PairingSystem.seq_streams + PairingSystem.ts_streams:
                packets = device.getOutputQueue(queueName).tryGetAll()
                if ps is not None:
                    ps.add_packets(packets, queueName)
                elif queueName == "color":
                    for packet in packets:
                          frame_q.put({"color": extract_frame[queueName](packet)})
                  if queueName == "color" and len(packets) > 0 and not args.prod:
                      cv2.imshow("preview", packets[-1].getCvFrame())`

**Comment by Erol444** [comment]
We found out that there was a memory leak in `gen2-recording` demo. The solution was to specify `Queue` size (eg. `queue = Queue(50)`). I will check in this project as well, thanks for reporting @nickjrz !

**Comment by nickjrz** [comment]
Awesome, that seems to work fine! thank you for your help! @Erol444

**Comment by Erol444** [comment]
Thanks for testing and confirming @nickjrz ! We will create a PR for it:)
