### ISSUE TITLE
Issue regarding conversion of model.json file to a .blob file

### ISSUE THREAD

**Issue by Zain-Gill123** [luxonis/depthai-experiments#190]
Hey! I am a complete newbie to this and I am trying to implement a pretrained model on the OAK-D. For that I have to convert the **model.json** file to a **.blob** but I am unable to find anything on it. 

I have also tried looking for a way to convert the **model.json** to **model.pb** but I got nothing to work with. 

Any type of help/resource would be highly appreciated!
-Zain

**Comment by Zain-Gill123** [comment]
@Erol444 Thank you for the response. I'll try the step and the tool and will update accordingly. 🙌

**Comment by YashRunwal** [comment]
@Zain-Gill123 I have a .blob file and want to deploy on Oak-D. Even I have an Anomaly detection model. How did you deploy it?

**Comment by Erol444** [comment]
> @Zain-Gill123 I have a .blob file and want to deploy on Oak-D. Even I have an Anomaly detection model. How did you deploy it?

Hello @YashRunwal , we will be adding documentation on this soon, for now you could start with the [efficientDet demo](https://github.com/luxonis/depthai-experiments/blob/master/gen2-efficientDet/main.py). 
Steps to use your custom model:
1) Change image size to match the model's input image size (line 26) and any potential configuration (RGB/BGR, interleaved..)
2) Change path to blob (in your case anomaly detection, line 34)
3) Change decoding for your model (lines 59 and onwards). In this case it's object detection model, and has 3 NN outputs; so we have `bb`, `label` and `conf` array, and we then decode these and display them on the frame.

Hopefully that helps!

**Comment by YashRunwal** [comment]
@Erol444 Wow, I wasn't expecting such a quick reply. Really appreciate it. I will try to use the information provided by you and try it and get back to you either tomorrow or on Thursday. Thanks again!

**Comment by Erol444** [comment]
Sounds good, thanks @YashRunwal !
