### ISSUE TITLE
KeyError: 'up4' when I run main.py of DepthAI-Inference-Engine!

### ISSUE THREAD

**Issue by Zain-Gill123** [luxonis/depthai-experiments#197]
So, I am converted my Pytorch model to OpenVino IR file (.xml and .bin files) and found it that triad running it on OAK-D but that did not work. So, I heard about DepthAI-Inference-Engine and that I could check if it works or not. 

Now, the issue is that I have run the code but it won't run and gives an error of **KeyError: 'up4'**. I could not find any viable solution via Google.  I am attaching the files and error message's image for reference. 
Any help would be appreciated!

**.XML and .BIN file and the Demo_Video**:
[model.zip](https://github.com/luxonis/depthai-experiments/files/7119260/model.zip)

**Error Image**:
![GitHub Post](https://user-images.githubusercontent.com/87517656/132291406-8fbe0f41-6ac2-46c2-b2f8-65fe129cae53.PNG)

**Comment by VanDavv** [comment]
Hi @Zain-Gill123, 

`up4` is the name of the output tensor from the neural network. I took a quick look at your model using https://netron.app/ and your output tensor's name should be `17/sink_port_0`

<img width="727" alt="Screenshot 2021-09-07 at 09 40 17" src="https://user-images.githubusercontent.com/5244214/132304882-40bd3085-4376-4367-a2c9-6f2c03cdc425.png">

you can also check the keys available in the `output` value by adding the following code before the failing line

```
print(list(output.keys()))
```

the name that will be printed should be the tensor's name. You can also just take the first tensor, no matter it's name, by using

```
data = next(iter(output.values()), None)
if data is None:
    raise RuntimeException("No output tensor returned!")
```

the `data` object here will contain the first output tensor (which in most cases will just be the only one anyways)

**Comment by Zain-Gill123** [comment]
Dear @VanDavv thank you for the quick response! I'll look into this issue and report back accordingly! The help is very appreciated buddy!
