### ISSUE TITLE
[Gen2] Facial Landmarks on DepthAI demo not working

### ISSUE THREAD

**Issue by BarnabasTakacs** [luxonis/depthai-experiments#245]
Hi,

It seems the [Gen2] Facial Landmarks on DepthAI demo does not work anymore.
It returns negative scores (running on Windows 10)

**Comment by Luxonis-Brandon** [comment]
Sorry about the trouble.  We'll investigate.

**Comment by tersekmatija** [comment]
Hey @BarnabasTakacs ,

if you were talking about the gen2-facemesh directory, you are indeed correct. There was a problem where I did not put sigmoid on the score. Should be fixed now with #246 . :)

**Comment by BarnabasTakacs** [comment]
Thank you for the quick response. It seems to work now. Will test it further and get back to you. Barnabas

**Comment by Erol444** [comment]
Closing the issue as it seems to be resolved.
