### ISSUE TITLE
MJPEG Streaming server connection refused

### ISSUE THREAD

**Issue by suciokhan** [luxonis/depthai-experiments#251]
I'm attempting to run the example mjpeg2 streamer script on my RPI 4, but I get a segmentation fault error & connection refused error.

`DepthAI is up & running. Navigate to 'localhost:8090' with Chrome to see the mjpeg stream
Unable to init server: Could not connect: Connection refused
Stack trace (most recent call last):
#1    Object "/lib/arm-linux-gnueabihf/libc.so.6", at 0xb6c7a11f, in 
#0    Object "/home/pi/.local/lib/python3.7/site-packages/depthai.cpython-37m-arm-linux-gnueabihf.so", at 0xb576293b, in backward::SignalHandling::sig_handler(int, siginfo_t*, void*)
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault
`

**Comment by suciokhan** [comment]
Upon further experimentation, it seems to be a problem with my DepthAI installation, rather than MJPEG-specific. The crash occurs in another script as soon as I execute getCvFrame().

**Comment by Erol444** [comment]
Hello @suciokhan , I have just tried it out on RPI4 4GB RAM RPI OS Bullseye (latest) with latest depthai version and it works as expected. I have only updated port number because there was something else running at 8090. Could you try updating both RPI OS and DepthAI version?
![image](https://user-images.githubusercontent.com/18037362/144448263-515cae02-7249-4fa2-a148-957f726a424a.png)

**Comment by suciokhan** [comment]
I'm working on updating depthai install- unfortunately there are so many options for updating it, I'm having trouble doing it the "right" way. I tried `sudo curl -fL https://docs.luxonis.com/install_dependencies.sh | bash` as described in https://docs.luxonis.com/projects/api/en/latest/install/#raspberry-pi-os. But after I ran that, now when I try my script Python tells me I have no module named 'cv2'. I downloaded the depthai repo and ran the install_requirements.py, and that runs and says it's skipping some stuff because I don't have opencv2 installed...uh, isn't that what the script is supposed to do for me? I'm pretty confused because I successfully installed it on a different RPI yesterday, but unfortunately can't recall which of these installation methods I used. Might have installed depthai from pip.

**Comment by Erol444** [comment]
You only need to install dependencies once, after that you can just update depthai library by `python3 -mpip install depthai -U`. Does the error with cv2 module still persist, even after installing requirements for `depthai` repo?

**Comment by suciokhan** [comment]
Yes.

**Comment by Erol444** [comment]
We have also created an image that has depthai/depthai-python installed (and all dependencies) that you can use:
https://drive.google.com/drive/folders/1O50jPpGj_82jkAokdrsG--k9OBQfMXK5?usp=sharing
`OAK_CM4_POE_V2.zip` is the one you would want to use for now.

**Comment by suciokhan** [comment]
This fixed my open-cv problem

`pip3 install --upgrade setuptools pip`

`pip3 install opencv-python`

Now it works...for whatever reason, doing sudo pip3 install opencv-contrib-python makes it hang up.

I decided to switch to using imagezmq for streaming the video from my RPI, and it's working. Thanks a lot for your tips @Erol444, next time I think I will try that image. However I had a bunch of other dependencies that were a challenge to install on this image and didn't want to spend another day or two re-installing those. Have a great day, and again, thanks very much for your super quick response!
