### ISSUE TITLE
gen2-yolop

### ISSUE THREAD

**Issue by chst12** [luxonis/depthai-experiments#265]
I am running the code of gen2-yolop with a OpenCV AI Kit: OAK—D.
I got the following error:
Traceback (most recent call last):
File "main.py", line 48, in <module>
NN_PATH = blobconverter.from_zoo(name="yolop_320x320", zoo_type="depthai")
File "C:\Users\CStel\AppData\Roaming\Python\Python38\site-packages\blobconverter\__init__.py", line 278, in from_zoo
return compile_blob(name, req_data=body, **kwargs)
TypeError: compile_blob() got an unexpected keyword argument 'zoo_type'

Any tips for this issue. Thanks in advance

**Comment by Erol444** [comment]
Hello @chst12 , that option was recently added, could you try updating your blobconverter?
`python -mpip install blobconverter -U`
Thanks, Erik

**Comment by chst12** [comment]
Thank you Erik
It works now

**Comment by themarpe** [comment]
(CC: @tersekmatija do the requirements reflect this dependency?)

**Comment by tersekmatija** [comment]
(@themarpe , yes, this was merged and updated during Yolo refactor [here](https://github.com/luxonis/depthai-experiments/tree/master/gen2-yolo/yolop))
