### ISSUE TITLE
gen2-deeplabv3_depth missing a file, "background.jpeg"

### ISSUE THREAD

**Issue by John-Dean** [luxonis/depthai-experiments#267]
Hi,

I just tried to launch the experiment gen2-deeplabv3_depth from the master branch and had the issue:

```Traceback (most recent call last):
  File "main.py", line 88, in <module>
    colorBackground = cv2.resize(crop_to_square(cv2.imread('background.jpeg')), (400,400))
  File "main.py", line 82, in crop_to_square
    height = frame.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```

Guessing "background.jpeg" hasn't been comitted?

Adding a black 400x400px jpeg file (attached) seems to fix this.
![background](https://user-images.githubusercontent.com/13804523/146679661-ea369baa-3403-4a7b-8cee-4986200480b7.jpeg)

Just a bit odd because one of the last commits was: https://github.com/luxonis/depthai-experiments/commit/fb6fde1ac9a46fc68843bcabd1ccd39340ebbe85 - "Updated & tested all experiments" would suggest to me a fault in the testing process assuming I haven't made a mistake.

Would it be possible to confirm the issue independently?

**Comment by Erol444** [comment]
Sorry about that @John-Dean , I have just merged https://github.com/luxonis/depthai-experiments/pull/258 PR that fixes that issue.

**Comment by John-Dean** [comment]
That's working great, thanks @Erol444 !
