### ISSUE TITLE
Not an Issue But a Question Re: Multi-Task Networks, i.e. Hydranet & DepthAI Support?

### ISSUE THREAD

**Issue by Marx-Melencio** [luxonis/depthai-experiments#278]
Hi @Luxonis-Brandon  ... I hope all's well! Just a general question regarding the possibility of DepthAI, i.e. Myriad and OpenVINO, being able to support multi-task networks like Hydranet? I'm back to focusing mainly on using DepthAI for our prototyping efforts at Aria. And I'm figuring out if this course here would be a good investment in learning multi-task networks, and possibly implementing something with DepthAI integration:  https://courses.thinkautonomous.ai/hydranets  ... More info about hydranets is found here:  https://openaccess.thecvf.com/content_cvpr_2018/papers/Mullapudi_HydraNets_Specialized_Dynamic_CVPR_2018_paper.pdf  ...  Greatly appreciate any recommendation from the community regarding this. Thanks!!!

**Comment by Erol444** [comment]
Hello @Marx-Melencio !
I would say in general it would be possible; you can run multiple NN models in parallel/series with our platform, example is [gaze-estimation](https://github.com/luxonis/depthai-experiments/tree/master/gen2-gaze-estimation#gen2-gaze-estimation) demo. As you can see in the graph, it runs 4 NN models for the final result. That said, I am not familiar with Hydranet at all, so I am not sure if **a)** layers are [all supported](https://docs.luxonis.com/en/latest/pages/model_conversion/#supported-layers), and **b)** what's the resource requirement for these models (do you need multiple GTX 3080s or can embedded AI accelerator like Myriad X run inference at realtime).
Thanks, Erik

**Comment by Marx-Melencio** [comment]
Thanks, @Erol444 !! I'll go ahead and test implementing multiple NNs running simultaneously, as it seems there won't be a need to use hydranets or other multi-task networks for this. Closing this now ...

**Comment by Erol444** [comment]
Oh and just to mentioned @Marx-Melencio , on the gaze estimation demo, only the initial face detection model could be the performance bottleneck; other models (head pose estimation, face landmarks estimation, gaze estimation models) aren't as computationally expensive. Looking at hydranet, I assume you would like to use segmentation together with mono depth estimation? We also have [YOLOP demo](https://github.com/luxonis/depthai-experiments/tree/master/gen2-yolo/yolop), which does object detection plus segmentation at around 5 FPS.
Thanks, Erik
