### ISSUE TITLE
Yolov5-On-Device-Decoding-Problem

### ISSUE THREAD

**Issue by YashRunwal** [luxonis/depthai-experiments#301]
Hello,

Need some help with On-Device-pretrained-Custom-YoloV5 Model.

I had a pretrained YoloV5 Model for 1 class with input size: 640x640. Then I followed this (https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/YoloV5_training.ipynb#scrollTo=0wAUjfvNT3r7) tutorial to prune the Onnx model and then used this prune model with this (http://blobconverter.luxonis.com/) tool with 4 shaves to convert to blob format. 

Then I followed on-device tutorial (https://github.com/luxonis/depthai-experiments/blob/master/gen2-yolo/device-decoding/main_api.py) and ran the script with the pruned model and edited json file (contains only 1 class and only 1 label). But I am getting the following error:

![image](https://user-images.githubusercontent.com/56769818/154495012-cf9a6813-eef8-4ee3-8f1b-350bb82b05d0.png)

Appreciate any help!!

**Comment by themarpe** [comment]
Hi @YashRunwal 
I think @tersekmatija will be able to help you out:)

**Comment by tersekmatija** [comment]
Hey @YashRunwal, are you using `depthai==2.14.1.0`? If not, could you try this version?

**Comment by YashRunwal** [comment]
@tersekmatija Hi, Yes. I checked the version and it is:
`DepthAi Version: 2.14.1.0.dev+27fa4519f289498e84768ab5229a1a45efb7e4df`

**Comment by YashRunwal** [comment]
I directly used the Online-Blobconverter with ONNX. I thought it will work because the online converter has an option to upload 'ONNX' model. But you think I should first convert it to xml and bin?

**Comment by YashRunwal** [comment]
@tersekmatija Hi, so I converted the `pruned.ONNX` model to `.xml `and `.bin`. And then converted to blob format using the command given in the Colab. I am still getting an error similar to the one mentioned above:

![image](https://user-images.githubusercontent.com/56769818/154920580-e59d350c-5511-4bcb-8def-94dd3885a6c7.png)

**Comment by tersekmatija** [comment]
@YashRunwal did you change the JSON that you are using when running the example accordingly (as written in the JSON section of the [device-decoding](https://github.com/luxonis/depthai-experiments/tree/master/gen2-yolo/device-decoding#jsons))?

Your nnconfig in the JSON should look like (edit anchors with your anchors):
```
    "nn_config":
    {
        "output_format" : "detection",
        "NN_family" : "YOLO",
        "input_size": "640x640",
        "NN_specific_metadata" :
        {
            "classes" : 1,
            "coordinates" : 4,
            "anchors" : [ANCHORS THAT YOU USE HERE],
            "anchor_masks" :
            {
                "side80" : [0,1,2],
                "side40" : [3,4,5],
                "side20" : [6,7,8]
            },
            "iou_threshold" : 0.5,
            "confidence_threshold" : 0.5
        }
    }
```

**Comment by YashRunwal** [comment]
@tersekmatija Hi, yes the config.json looks exactly like yours:
```
{
    "nn_config":
    {
        "output_format" : "detection",
        "NN_family" : "YOLO",
        "input_size": "640x640",
        "NN_specific_metadata" :
        {
            "classes" : 1,
            "coordinates" : 4,
            "anchors" : [10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326],
            "anchor_masks" :
            {
                "side52" : [0,1,2],
                "side26" : [3,4,5],
                "side13" : [6,7,8]
            },
            "iou_threshold" : 0.5,
            "confidence_threshold" : 0.5
        }
    },
    "mappings":
    {
        "labels":
        [
            "class_A"        
        ]
    }
}

```

**Comment by tersekmatija** [comment]
Anchors should be OK then. Side numbers are not. See 80, 40, 20 instead of 52, 26, 13. That's what the error is telling you as well :)
```
                "side80" : [0,1,2],
                "side40" : [3,4,5],
                "side20" : [6,7,8]
```

**Comment by YashRunwal** [comment]
I changed that too (I shared the unchanged Config before, sorry). My new config has the following:
![image](https://user-images.githubusercontent.com/56769818/154975435-75c6364b-6694-471b-b29d-869015296d40.png)
The error persists.

**Comment by tersekmatija** [comment]
@YashRunwal Are you passing the config when you run the main.py or main_api.py? How do you start the script?

**Comment by YashRunwal** [comment]
@tersekmatija `python main_api.py -m custom_yolo.blob -c custom_yolo.json `

I also tried using `main.py script` but get another error:
![image](https://user-images.githubusercontent.com/56769818/154986684-29af457c-a84e-4c6d-b616-6da74b3d7bbc.png)
For this I tried inserting the following line in the main.py script:
`pm.pipeline.create(dai.node.ImageManip).setMaxOutputFrameSize(1228800)`, however the error is still there.

So it doesn't work either with `main_api `or `main`

**Comment by tersekmatija** [comment]
On `main_api.py` the error is the same as before? Can you send me the zip via GoogleDrive of the:
* model weights (.pt), 
* onnx, 
* XML and BIN, 
* blob,
* and the JSON,
* test image?

**Comment by YashRunwal** [comment]
@tersekmatija It worked. Sorry for the late reply. Was quite busy yesterday. The problem was that, I accidentally commented a line and hence depthai threw the error that anchors are not set. Was my fault to be honest. Thanks but also I apologize. I'll be back with more doubts :) hahah

**Comment by tersekmatija** [comment]
Np, glad to see it resolved :)

**Comment by potSm0ker** [comment]
i think a regular webcam may be better suited for running yolov5 custom models, this is a bunch of extra steps to get to the same place. I am not sure i should have bought this oak d pro now, probably could have got cheaper and easier to use camera...

**Comment by tersekmatija** [comment]
@potSm0ker Well, it depends. If a webcam works for you, then you haven't really had the need for some embedded device that can run AI on it anyway.

But, the process of running Yolo on OAK-D should be relatively easy:
1/ You train a model (you have to do this anyway for a webcam)
2/ You upload the .pt weights to [tools.luxonis.com](https://tools.luxonis.com/)
3/ You use main_api.py or SDK to run the Yolo using the blob and JSON you get from tools
