### ISSUE TITLE
gen2-yolo/host-decoding yolov5s_sku model wrong output

### ISSUE THREAD

**Issue by ibaiGorordo** [luxonis/depthai-experiments#313]
### **Example**
- gen2-yolo/host-decoding/main.py

### **Model**
- yolov5s_sku_openvino_2021.4_6shave.blob

### **Description**
It seems that the output of the default model (**yolov5s_sku_openvino_2021.4_6shave.blob**) in the **gen2-yolo/host-decoding** example has some issue. 

The code runs properly, but it only detects small bounding boxes and it seems to like detecting keyboard keys (image below).

The rest of the models (default models) seem to work fine though. 

![FMuuz_FagAASbNZ](https://user-images.githubusercontent.com/43162939/156094961-d51b9afe-95db-4e7c-8803-1fe90008cbac.png)

**Comment by Erol444** [comment]
Hello @ibaiGorordo,
I believe that model was trained on shopping shelves, and it detects whether there is an item on the shelf (or if it's empty), that's why it detects only "small bounding boxes".
cc @tersekmatija  to confirm.
Thanks, Erik

**Comment by tersekmatija** [comment]
Yes, the SKU model is pretrained on shopping shelves. It's from the accompanying tutorial, that's why it's set as default. The other 2 models are YoloV5 S and M models pretrained on COCO, provided in Ultralytic's YoloV5 repository :)

**Comment by ibaiGorordo** [comment]
My bad, I thought the sku referred to some version of Yolov5. That makes sense why it liked the small objects that are close to each other.

Thank you for the explanation!
