### ISSUE TITLE
OAK-d Lite Rotate -90 Dgree

### ISSUE THREAD

**Issue by rexn8r** [luxonis/depthai-experiments#326]
Hello Erik & Team,

I am trying to run depthai on OAK-D lite positioned @ -90 degree as per the image below;
![oak-d](https://user-images.githubusercontent.com/12812556/158962810-41912f1e-92e2-4213-acef-7eb0af907820.jpg)

The depth value is OK when face is in the center as per following image;
![center](https://user-images.githubusercontent.com/12812556/158964029-0b1e2055-ff06-4820-937e-7f34561e4b4d.png)

The depth value is wrong when face is at the edge of the camera on either side as per following image;
![side](https://user-images.githubusercontent.com/12812556/158964165-607c7657-4e49-4da1-b8e1-3b5b38b856a7.png)

I have got another script where -90 degree rotation is not used and the video size if 300 X 300 and the depth value comes out correct whether the face is in the center or at the edge of the screen as per following images;

![300-center](https://user-images.githubusercontent.com/12812556/158964372-b26247e1-e3b2-4df4-9b1c-2788c3a5c399.png)
![300-side](https://user-images.githubusercontent.com/12812556/158964455-2ddce4a7-15e4-465f-b8c5-7de5d2b938d2.png)

In the production environment, I would like to rotate the camera to fit in the hardware which will host the camera.

would you be able to check the python script and let me know how to resolve the depth issue? also it has multi neural networks  from face detection to depth then age & gender and finally emotion. I would appreciate if you can also look at the code and let me know if its correct way of implementing multi stage NN or not.

thanks
rex

**Comment by themarpe** [comment]
CC: @Erol444

**Comment by Erol444** [comment]
Hello @rexn8r,
Could you share the minimal reproducible code in gist or pastebin?
Thanks, Erik

**Comment by rexn8r** [comment]
Hi @Erol444 

thanks for your response.

below is the link for detection with -90 degree rotation;

https://pastebin.com/ufkbJQfS

below is the link for detection without rotation;

https://pastebin.com/kMnkW3Lc

thanks
rex

**Comment by Erol444** [comment]
Hello @rexn8r , The problem is that you are rotating left/right frames before they are sent to the StereoDepth node, which doesn't work (due to disparity matching happening only horizontally in the hardware-accelerated block on silicon). You would need to either change the convert bounding box from a vertical to a horizontal position or rotate the depth map after the StereoDepth node calculates it.

**Comment by rexn8r** [comment]
Hi @Erol444 

Thanks for your response.

To be honest, your api is quite overwhelming and not straight forward to understand for someone who has no previous AI experience or has limited exposure to AI jargons. 

Will I need to use script node to rotate the image back to horizontal position for depth calculation? 

I did try to use script node (for multi nn) but couldn't get it going.

Pointer to any example would be appreciated.

We are looking to use oak-d in our digital signage solution for client's project where it will be used with custom hardware for sizable rollout. But looking at the complexity of your api to implement multi nn solution with rotation, it seems we will have to look out for other API as we are unable to achieve the desired results.

Thanks

**Comment by rexn8r** [comment]
hi erik

I have implemented the stereo depth code based on the following example from the API documentation;

https://docs.luxonis.com/projects/api/en/latest/samples/ImageManip/image_manip_rotate/?highlight=rotate

But you say the rotation is done before they are sent to steriodepth node. 

This is what i mean by my comment " your api is quite overwhelming and not straight forward to understand" and the frustrating part is the response I get is no clear cut reference to example or code sample to follow. Many of your gen2 samples do not work and throws legacy errors. 

For a 3rd party developers having limited AI experience, who would like to integrate AI functions with their own software solution, there is no step by step guide to follow to create real world solution like how to implement multiple neural networks along with depth, how and when to use script node or how to run multiple NN either on device or host side with optimum performance. 

For a start up company like us, who can't afford Luxonis technical support (I have a formal quote) would expect your API documentation to include more real world examples or guide so it can be implemented with limited AI knowledge and it will be win/win situation otherwise will loose potential business.

thanks
raxit

**Comment by Erol444** [comment]
Hello @rexn8r , I apologize for the inconvenience about our API. Regarding the multi-NN (one after the other/in series/2stage inference), we have a couple of examples:
- [Age/gender recognition](https://github.com/luxonis/depthai-experiments/tree/master/gen2-age-gender)
- [Emotion recognition](https://github.com/luxonis/depthai-experiments/tree/master/gen2-emotion-recognition)
- (3 stage NN) [Face recognition ](https://github.com/luxonis/depthai-experiments/tree/master/gen2-face-recognition)
- [Face landmark detection](https://github.com/luxonis/depthai-experiments/blob/syncing/gen2-syncing/2stage-nn-sync.py)

Regarding `Many of your gen2 samples do not work and throws legacy errors.`, could you please point out which demos throw an error so we can correct them?

Regarding using the `spatial detection network` with a rotated camera, I will try to prepare a demo soon and share it.
Thanks, Erik

**Comment by Erol444** [comment]
After additional testing, we have noticed that Spatial Detection Network doesn't (yet) work with rotated depth. See script [here](https://gist.github.com/Erol444/0d558023bd1ea47900e1b19536da1d69). You would need to use `image_manip_refactor` branch to rotate the depth (raw16) frame. I have already shared results with the firmware team and are discussing how to support this (rotated OAK) use case. Video below.

https://user-images.githubusercontent.com/18037362/159120030-5d8e1daf-f635-4e3e-8bc2-acbdadce5350.mp4

**Comment by rexn8r** [comment]
hi @Erol444 

thanks for your response. yes i did try to rotate 300 X 300 preview to -90 degree and i was getting same results. in documentation, it's mentioned that width value needs to be in multiple of 16 so i thought this is not possible.

https://docs.luxonis.com/projects/api/en/v2.11.0/samples/image_manip_rotate/

is there any time frame to support this feature? our hardware needs to go in production for first pilot in May. the placement of camera depends upon this feature, hence asking..

thanks

**Comment by Erol444** [comment]
Hello @rexn8r ,
There are also other ways of achieving this functionality. You could send unrotated depth maps to the host and then calculate special coordinates of objects on the host, see [calc-spatialson-host demo](https://github.com/luxonis/depthai-experiments/tree/master/gen2-calc-spatials-on-host). You would then only rotate color frames on the device, run inference (non-spatial), and send object detection results to the host. On host you would first recalculate bounding boxes of objects (from vertical to horizontal position) and get spatial coordinates of objects with the `calc-spatialson-host` approach.
Thanks, Erik

**Comment by szabi-luxonis** [comment]
@rexn8r we will add support for it before may, likely this week. I will let you know.

**Comment by rexn8r** [comment]
hi @szabi-luxonis 

any update on this issue?

thanks
rex

**Comment by szabi-luxonis** [comment]
hello @rexn8r 

Sorry for a long turnaround on this, a lot of things going on.

Install a custom library for -90 degree rotation:
```
python3 -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8"
```
The library will be ready in 20-30 min, you can follow it [here](https://github.com/luxonis/depthai-python/actions/runs/2309718566)

Tested with the following code:
https://gist.github.com/szabi-luxonis/247937f3740e86fe70832860da9c8e78

![image](https://user-images.githubusercontent.com/60790666/167948736-ae52d511-c84a-4076-94bc-61fd2923e9d6.png)

**Comment by rexn8r** [comment]
hi @szabi-luxonis 

works like a charm ! thanks for that. much appreciate.

Now trying with latest age-gender demo (with MultiMsgSync.py) but on start up it gets stuck.

Here's the modified main.py script;

https://pastebin.com/r0gSpeY8

am i missing something??

thanks
rex

**Comment by rexn8r** [comment]
hi @szabi-luxonis 

i ran following script for about 10 minutes;

https://gist.github.com/szabi-luxonis/247937f3740e86fe70832860da9c8e78

it crashed with following error;

[184430101152691200] [539.368] [system] [critical] Temperature above 105C. Device will shutdown if not reduced. Note: If this is unexpected please reach out to support@luxonis.com to discuss/debug.

the room temperature is about 22 Celsius.

rex

**Comment by szabi-luxonis** [comment]
hello @rexn8r 
We had a limited batch of OAK-D-LItes with HW issues which results in device overheat.
Reach out to [support@luxonis.com](mailto:support@luxonis.com) to discuss/debug/replacement.

**Comment by rexn8r** [comment]
> hi @szabi-luxonis
> 
> works like a charm ! thanks for that. much appreciate.
> 
> Now trying with latest age-gender demo (with MultiMsgSync.py) but on start up it gets stuck.
> 
> Here's the modified main.py script;
> 
> https://pastebin.com/r0gSpeY8
> 
> am i missing something??
> 
> thanks rex

Thanks @szabi-luxonis 

Any pointers to this issue?

Thanks

**Comment by rexn8r** [comment]
hi @szabi-luxonis 

ok I will try https://pastebin.com/r0gSpeY8 on another pc.

final question, will the custom library for -90 degree rotation be part of the main branch? 

thanks
rex

**Comment by szabi-luxonis** [comment]
@rexn8r 

Indeed, in some cases it got stuck at startup, in other it worked, timing related.
There is a fundamental flaw of the syncing mechanism, which assumes that preview sequence numbers are always equal or higher than detection sequence numbers, the queue fills up, blocks all the frames in the pool and the pipeline gets stuck (deadlock). I would suggest a different syncing mechanism which doesn't make assumptions.

[Here](https://gist.github.com/szabi-luxonis/a406aa5290bf2961b8f2e58485fe3f0f) is a workaround.

> final question, will the custom library for -90 degree rotation be part of the main branch?

It might make into main at some point.

**Comment by rexn8r** [comment]
Hi @szabi-luxonis 

Thanks for the workaround.

Regards
Rex
