### ISSUE TITLE
`gen2-record-replay` aligned depth possible?

### ISSUE THREAD

**Issue by JojoDevel** [luxonis/depthai-experiments#329]
Is it possible to obtain aligned depth & rgb from recodings? It works for me in real-time using depthai-python [example](https://github.com/luxonis/depthai-python/blob/main/examples/StereoDepth/rgb_depth_aligned.py).

But in replay when adding
```python
nodes.stereo.setDepthAlign(dai.CameraBoardSocket.RGB)
```
to the replay pipeline below this line https://github.com/luxonis/depthai-experiments/blob/6ff9247d04661ea3ea435c210e230facc6fe2ee4/gen2-record-replay/libraries/depthai_replay.py#L109
I get
```
[1844301081DA6B1200] [153.761] [StereoDepth(3)] [warning] Align to RGB requested, but ColorCamera not configured. Using MonoCamera resolution
```
and the rgb seems not to be aligned to the depth frame...

**Comment by themarpe** [comment]
@JojoDevel 
You'll have to explicitly set the output disparity width/height to match that of the ColorCamera.
CC: @Erol444 (these will have to be saved over to be able to replay in same manner as well)

**Comment by JojoDevel** [comment]
Nice that works pretty good :rocket:  I recorded 1080p and when I use
```python
node.stereo.setOutputSize(1920, 1080)
```
the disparty map is aligned with my RGB and my yolo detections :+1: 
Also works with downscaled resolutions (e.g. factor 2): `(960, 540)` and saves performance and data bandwidth.

**Comment by Erol444** [comment]
Abstracted in DepthAI SDK using [Replaying](https://docs.luxonis.com/projects/sdk/en/latest/features/replaying/) functionality.
