### ISSUE TITLE
Error running gen2-people-tracker

### ISSUE THREAD

**Issue by vipulkumar-developer** [luxonis/depthai-experiments#332]
When I try to run the main.py file of the project gen2-people-tracker, this error comes out:

`[14442C10310D57D700] [858.425] [Script(3)] [critical] AttributeError: 'lpb.Buffer' object has no attribute 'setData'`

Iìm working with an OAK-D IOT and I0m working with both gen2-people-tracker and with SPI part that can be found in this link https://github.com/luxonis/esp32-spi-message-demo/tree/main/people_tracker

**Comment by Erol444** [comment]
This should be resolved by using newer `depthai` library version.
