### ISSUE TITLE
Fatal error on MSS CPU: trap: 09, address: 8026E80C

### ISSUE THREAD

**Issue by holgerkoch** [luxonis/depthai-experiments#334]
Hi,
i have a oak-1 camera and the depthai_demo.py runs perfect. So i think, a have all requirements are fullfilled and i have no hardware issue.
But when i try to start some example from the depthai-experiments, for example the gen2-emotion-recognition, i got the following error message:

(myvenv) hko@zeus-ubuntu:~/depthai-experiments/gen2-emotion-recognition$ python3 main.py
Creating Color Camera...
Creating Face Detection Neural Network...
[14442C1011533FD700] [219.914] [system] [critical] Fatal error. Please report to developers. Log: 'Fatal error on MSS CPU: trap: 09, address: 8026E80C' '0'
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    with dai.Device(pipeline) as device:
depthai.XLinkReadError: Couldn't read data from stream: '__rpc_main' (X_LINK_ERROR)

The installation looks good for me:
(myvenv) hko@zeus-ubuntu:~/depthai-experiments/gen2-emotion-recognition$ python3 -m pip install -r requirements.txt
Requirement already satisfied: opencv-python==4.5.1.48 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (4.5.1.48)
Requirement already satisfied: depthai==2.15.1.0 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (2.15.1.0)
Requirement already satisfied: blobconverter==1.2.9 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (1.2.9)
Requirement already satisfied: numpy in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (1.19.5)
Requirement already satisfied: requests in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from blobconverter==1.2.9->-r requirements.txt (line 3)) (2.27.1)
Requirement already satisfied: boto3 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from blobconverter==1.2.9->-r requirements.txt (line 3)) (1.17.39)
Requirement already satisfied: PyYAML in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from blobconverter==1.2.9->-r requirements.txt (line 3)) (6.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from boto3->blobconverter==1.2.9->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: botocore<1.21.0,>=1.20.39 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from boto3->blobconverter==1.2.9->-r requirements.txt (line 3)) (1.20.112)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from boto3->blobconverter==1.2.9->-r requirements.txt (line 3)) (0.3.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from requests->blobconverter==1.2.9->-r requirements.txt (line 3)) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from requests->blobconverter==1.2.9->-r requirements.txt (line 3)) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from requests->blobconverter==1.2.9->-r requirements.txt (line 3)) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from requests->blobconverter==1.2.9->-r requirements.txt (line 3)) (2021.10.8)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from botocore<1.21.0,>=1.20.39->boto3->blobconverter==1.2.9->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/hko/depthai-experiments/myvenv/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.21.0,>=1.20.39->boto3->blobconverter==1.2.9->-r requirements.txt (line 3)) (1.16.0)

I google and try many hours, but i have no idea, what i can do. Did anybody have a hint for me?

Best regards

Holger Koch

**Comment by Luxonis-Brandon** [comment]
Sorry about the trouble here.  I'll need @Erol444 's help here.  Not sure what is going on here.

**Comment by Erol444** [comment]
Hello @holgerkoch ,
By default, this demo will also show spatial coordinates (Z component of XYZ) of the face, as seen on the [demo img](https://github.com/luxonis/depthai-experiments/tree/master/gen2-emotion-recognition). OAK-1 doesn't have stereo depth perception, so I believe that's the reason for this strange crash - I agree that firmware should provide a better error message. Let me try removing the spatial part of the pipeline and do a quick PR.
Thanks, Erik

**Comment by Erol444** [comment]
Hello @holgerkoch ,
I have added checks whether the OAK has stereo camera pair, and in such case, it disables getting spatial coordinates. Could you try [this PR](https://github.com/luxonis/depthai-experiments/pull/336)?
Thanks, Erik

**Comment by holgerkoch** [comment]
Hello @Erol444,
thank you very much for your fast help. You hit exactly the point and now it is working.

(myvenv) hko@zeus-ubuntu:~/depthai-experiments-pr/depthai-experiments/gen2-emotion-recognition$ python3 main.py 
Creating Color Camera...
OAK-1 detected, app won't display spatial coordiantes

(myvenv) hko@zeus-ubuntu:~/depthai-experiments-pr/depthai-experiments/gen2-age-gender$ python3 main.py 
Creating Color Camera...
OAK-1 detected, app won't display spatial coordiantes
Creating Age Gender Neural Network...

Thank you very much for your great work.


Best regards

Holger Koch
