### ISSUE TITLE
gen2-camera-demo: inStreamsCameraID never used realy 

### ISSUE THREAD

**Issue by netzzwergeGithub** [luxonis/depthai-experiments#338]
The variable 'inStreamsCameraID ' is initialized in in line 259 and constantly set to the same values in the for loop (line 263).

But I didn't find any other place in the file where it is used.

https://github.com/luxonis/depthai-experiments/blob/50eeabbf6572f8d25e5d26be3f26923b9a4f0e7a/gen2-camera-demo/main.py#L259

**Comment by themarpe** [comment]
@netzzwergeGithub its used later in https://github.com/luxonis/depthai-experiments/blob/50eeabbf6572f8d25e5d26be3f26923b9a4f0e7a/gen2-camera-demo/main.py#L288 
Which sets which camera the node should use.

**Comment by netzzwergeGithub** [comment]
Sorry I oversaw that  using.
