### ISSUE TITLE
gen2-ocr: AttributeError: NNData.getSequenceNum()

### ISSUE THREAD

**Issue by tcbennun** [luxonis/depthai-experiments#339]
I'm using the OAK-D-IoT-75 connected to a USB 3 port on my Debian Linux machine.

I've had plenty of success with demos in the `depthai-python` repository.

But with this one, after the blobs are downloaded and pipelines set up, I get:

```
Traceback (most recent call last):
  File "/home/tcb/build/depthai-experiments/gen2-ocr/main.py", line 196, in <module>
    frame = host_sync.get_msg(in_det.getSequenceNum()).getCvFrame().copy()
AttributeError: 'depthai.NNData' object has no attribute 'getSequenceNum'
```

Here are some steps to recreate:

```
git clone --recurse-submodules https://github.com/luxonis/depthai-experiments.git
cd depthai-experiments/gen2-ocr
python3 -m virtualenv ./venv
source ./venv/bin/activate
python3 -m pip install -r requirements.txt
python3 main.py
```

I stuck a `print(dir(in_det))` in there, and the object seems to have (most of?) the other methods listed in [the docs](https://docs.luxonis.com/projects/api/en/latest/components/messages/nn_data/), but not `getSequenceNum`. What gives?

**Comment by eugemaf** [comment]
I've seen that uninstalling depthai-2.13.3.0 and installing depthai-2.15.1.0 it works!

**Comment by themarpe** [comment]
Thanks for report - we'll test and update the library requirement across experiments:)
