### ISSUE TITLE
sbd_mask_tutorial does not run properly

### ISSUE THREAD

**Issue by kannwism** [luxonis/depthai-experiments#366]
Hi!

I am trying to follow the [Deploying Custom Model Tutorial](https://docs.luxonis.com/en/latest/pages/tutorials/deploying-custom-model/).

I can run gen2-age-gender on my OAK-D Lite smoothly. However after following the tutorial the output freezes after the first frame. I get the same behavior if I checkout branch `DONT_DELETE_sbd_mask_tutorial`.

There is no helpful error in the console:
![image](https://user-images.githubusercontent.com/18029781/173081686-d4f68839-80c3-4e86-857b-f2bfa705c3b0.png)

I installed the requirements.txt.

Otherwise I'm on Python 3.8.10 and Ubuntu 20.04.

Any help appreciated!

**Comment by Erol444** [comment]
@kannwism  Trying it out now, I apologize for the inconvenience...

**Comment by Erol444** [comment]
Hi @kannwism , I apologize for the delay, I didn't realize this is the same issue as other multi-stage NN. Works in the [PR here](https://github.com/luxonis/depthai-experiments/pull/379).

**Comment by kannwism** [comment]
No worries. Thank you for fixing it! I'm currently working on a different topic, so I don't have the time to try it out again at the moment.
