### ISSUE TITLE
90 Degree Rotation Wrong Gender Detection

### ISSUE THREAD

**Issue by rexn8r** [luxonis/depthai-experiments#375]
Hello

please check the following code having -90 degree camera rotation with age-gender demo.

https://pastebin.com/KyK6t99e

It doesn't recognize female. 

if i use dai.NNData() instead of the script node, then i get correct result.

please help.

thanks
rex

**Comment by Erol444** [comment]
Hi @rexn8r ,
Could you elaborate what you mean with `if i use dai.NNData() instead of the script node`? Do you mean sending the rotated frame of the face directly via NNData to recognition network?
Thanks, Erik

**Comment by rexn8r** [comment]
hi @Erol444 

thanks for your response.

please check the code from following link where NNData is used for inference instead of script node.

https://pastebin.com/NsbKzEkD

By the way i am using following PR provided by @szabi-luxonis in  #326 

python3 -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8"

looking forward to your assistance.

thanks
rex

**Comment by rexn8r** [comment]
hi @Erol444 

finally i have managed to get the detected face frame correctly with -90 degree rotation.

https://pastebin.com/8bTfFEkS

**#cam.preview.link(image_manip_script.inputs['preview']) -->> commented this line as it was passing frame in landscape mode** 

**manipRgb.out.link(image_manip_script.inputs['preview']) -->> added this line so the script node is getting -90 degree rotated frame from the camera**

if you run the code, it will now show correct cropped detected face wherever it is in the view. and it seems the gender information is also now correct.

**Question : Is this the correct way of passing data to the script node????**

some times the program throws following error;

[18443010E14D1EF500] [249.894] [ImageManip(12)] [error] Processing failed, potentially unsupported config

i have following PR installed provided by @szabi-luxonis  which i think addresses the edge correction;

python3 -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8"

any idea what could be the reason?

thanks.
Rex

**Comment by rexn8r** [comment]
hello depthai experts,

I am trying to put up a python script to do following tasks using OAK-D Lite (3 stage nn);

-- Face Detection
    |__ Age / Gender Detection
         |__  Expression Detection

The camera is rotated @ -90 degrees.

I have created a python script using gen2 age/gender/expression demo along with modifications to MultiMsgSync.py as per the code described in the link below;

**detection script code;**

https://pastebin.com/2ib34hqH

**MultiMsgSyncV2.py code;**

https://pastebin.com/VAmD2WwU

**The problem:**

1. Some time it throws **Processing failed, potentially unsupported config** error.
2. if multiple faces are in front of the camera then **msgs = sync.get_msgs()** returns none and the script doesn't work there on i.e. it gets stuck on the last frame

I have following PR installed which has fix for the edge problem on the -90 degree rotated camera;

python3 -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8"

I would highly appreciate if some expert can throw a light on where could be the problem in the code. 

thanks
rex

**Comment by rexn8r** [comment]
.
