### ISSUE TITLE
OAK-D Lite Temperature reach to 105c in 15 min

### ISSUE THREAD

**Issue by rexn8r** [luxonis/depthai-experiments#386]
Hello

We have 3 OAD-D Lite Camera and we have 3 PCs (2 Linux & 1 Windows)

Windows PC Spec;

![image](https://user-images.githubusercontent.com/12812556/183601450-a8ddf797-490b-4a36-947a-4e22f166e566.png)

Ubuntu PC Specs;

![image](https://user-images.githubusercontent.com/12812556/183601707-d4c95171-f732-49cf-81d4-d56abc037a89.png)

We downloaded gen2-age-gender demo files and setup depthai using requirements.txt (version 2.17.3)

The camera temperature shoot up to 105c on all of them within 15-20 minutes and crash out. The room temperature was 21c 

![image](https://user-images.githubusercontent.com/12812556/183609276-d954da24-ae40-463a-9ea2-72cc1da87fb9.png)

What could be the reason for the device to heat up so quickly? 

thanks

**Comment by Erol444** [comment]
Hello @rexn8r ,
We apologize for the inconvenience. As it looks like a hardware fault (more [details here](https://github.com/luxonis/depthai-python/issues/522#issuecomment-1058524557)), could you please send an email to support@luxonis.com so we can resolve this quickly?
Thanks, Erik

**Comment by rexn8r** [comment]
Hi @Erol444 

email sent @ support.

Thanks

**Comment by cafemoloko** [comment]
Thanks, @rexn8r , I got an email and will proceed accordingly.

**Comment by laitathei** [comment]
I also have this problem when i inference the yolov4 model with oakd-lite. Is it the same problem with @rexn8r ?

**Comment by cafemoloko** [comment]
@laitathei would you mind shooting an email to support@luxonis.com? we'll look into this.
