### ISSUE TITLE
INFO: point-cloud-projection depthAI branch information 

### ISSUE THREAD

**Issue by nullbyte91** [luxonis/depthai-experiments#4]
Hi @saching13,

I'm using the latest version of depthAI package and trying to explore on your point cloud implementation. There are some interface changes between your Point cloud branch and the master branch. I've merged depthAI changes to master depthAI demo, but I have an issue with calibration changes. 

Could you please provide me with the branch name or commit_id that works for you.

Regards,
Jegathesan S

**Comment by saching13** [comment]
Hey, This is working in depthai 0.1.0 version and depthai 0.2.0 has changed and this file doesn't work on that as of now. (if you have depthai_demo.py it's 0.2.0).
That being said. [Here](https://github.com/luxonis/depthai/tree/develop) is another branch which comes with pcl included
In this branch to make it work you need to have the new updated calibration. you can test if your device has new two hompgrahy calibration by checking the EEPROM version which is printed when the device starts. you can update this by recalibrating too. In the mean time I i will update this with the current main branch.

**Comment by VanDavv** [comment]
Hi @nullbyte91, the point-cloud-projection has been migrated to the new API and merged to master in #6 . Could you give it a try and confirm if it works?

**Comment by nullbyte91** [comment]
@VanDavv @saching13 
As expected, I was getting the EEPROM error. I tried re calibration for the modular camera(BW1098FFC), then I tried writing them to EEPROM, and got the core dump when I executed the below command.

```bash
python3 depthai_demo.py --store-eeprom -brd bw1098ffc

Calibration file is outdated. Re calibration required before writing to EEPROM.
To continue using old calibration disable('-e') write to EEPROM.[1]    28342 abort (core dumped)  python3 depthai_demo.py --store-eeprom -brd bw1098ffc
```
FYI. I've not tried the EEPROM writing before so not sure what might be the issue. And, I'm using master branch for both depthai and depthai-experiments repo.

**Comment by saching13** [comment]
Hey @nullbyte91 could you checkout to develop branch. (it looks like you are already on develop branch) so if you want to write to EEPROM on develop branch you need to recalibrate. if you have previously calibrated and didn't delete the images captured and stored in the dataset folder you can just run `python3 calibrate.py -s [sq size] -brd bw1098ffc -m process`. once you have done that you should be able to overcome that error on store EEPROM.

**Comment by VanDavv** [comment]
@nullbyte91 can we close this issue? Did @saching13 suggestion work?

**Comment by nullbyte91** [comment]
@VanDavv I tried twice some times back but didn't work for me. Give me a day I can test and update the same. Thanks.
