### ISSUE TITLE
git clone error: invalid path 

### ISSUE THREAD

**Issue by richard-xx** [luxonis/depthai-experiments#423]
When cloning this repository on WINDOWS, there are some errors and it seems that the file name contains invalid characters, such as `:`.

```shell
error: invalid path 'depth-test_z-acc_spatial-noise/point-clouds/Camera: Astra.ply'
error: invalid path 'depth-test_z-acc_spatial-noise/point-clouds/Camera: OAK.ply'
```

I think the invalid characters in the file name should be changed to other characters

**Comment by njezersek** [comment]
Thanks for catching that. I accidentally added some unfinished code to the pull request.
