### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiMsgSync'

### ISSUE THREAD

**Issue by DrBwts** [luxonis/depthai-experiments#430]
Hi,

I'm trying to run Gen2 Emotion recognition on a Raspberry Pi 4B. 

I've installed depthai, tested it & its working but when I run your code I get,

_ModuleNotFoundError: No module named 'MultiMsgSync'_

I looked at the requirements & this module isn't listed & I cant find it on _pip_. Where do I get it from?

Thanks

Nic

**Comment by DrBwts** [comment]
I found it duhh

**Comment by Erol444** [comment]
@ilyaGasanFrontend are you using the depthai-sdk as specified in requirements.txt in gen2-emotion-recognition folder?
