### ISSUE TITLE
Unable to install depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8 on Windows 10

### ISSUE THREAD

**Issue by rexn8r** [luxonis/depthai-experiments#449]
Hello

I have been trying to install following depthai version on Windows 10 but it throws CMAKE errors.

python -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8"

I followed manual installation steps provided on the following link on a fresh windows 10 system;

https://docs.luxonis.com/projects/api/en/latest/install/#windows-10

I also added C:\Program Files\CMake\Bin folder in the "Path" section in the environment variables.

![image](https://user-images.githubusercontent.com/12812556/213858647-293960da-82f1-4d64-94fc-f7f59fa53dfb.png)

The reason to install version depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8 is that I am trying to implement -90 degree camera rotation.

please help to solve the problem

thanks
rex

**Comment by Erol444** [comment]
Hi @rexn8r ,
Which demo requires you to use the custom 2.15.4 branch/build?
Thanks, Erik

**Comment by rexn8r** [comment]
Hi @Erol444 

I am using oak-d camera with -99 degree rotation for age and gender

https://github.com/luxonis/depthai-experiments/issues/326#issuecomment-1124301011

This PR was provided by @szabi-luxonis 

If I use the latest 2.19 release, the age and gender inferences are wrong with -90 degree rotation.

I am trying to install this PR on windows 10 but getting "failed building wheel" error despite installing CMake library, adding CMake path in the environment variables, and also installing c++ for CMake via visual studio build tools set up.

Do i need to install visual studio build tools first and then execute manual depthai installation commands in the windows powershell?

Thanks

**Comment by rexn8r** [comment]
Ok so found solution.

Installed Python 3.8

Installed CMake 3.21.2

Installed Visual Studio build tools 2017

now I can install depthai 2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8

With depthai latest release, if I rotate the camera to -90 degrees, the Z value coming out wrong.

MRE:

monoLeft = pipeline.create(dai.node.MonoCamera)
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)

monoRight = pipeline.create(dai.node.MonoCamera)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)

stereo = pipeline.create(dai.node.StereoDepth)
stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
stereo.setLeftRightCheck(True)
stereo.setDepthAlign(dai.CameraBoardSocket.RGB)
stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
stereo.setExtendedDisparity(True)
stereo.setSubpixel(False)

manipLeft = pipeline.create(dai.node.ImageManip)
rrL = dai.RotatedRect()
rrL.center.x, rrL.center.y = monoLeft.getResolutionWidth() // 2, monoLeft.getResolutionHeight() // 2
rrL.size.width, rrL.size.height = monoLeft.getResolutionHeight(), monoLeft.getResolutionWidth()
rrL.angle = -90
manipLeft.initialConfig.setCropRotatedRect(rrL, False)
manipLeft.inputConfig.setWaitForMessage(False)
monoLeft.out.link(manipLeft.inputImage)

manipRight = pipeline.create(dai.node.ImageManip)
rrL = dai.RotatedRect()
rrL.center.x, rrL.center.y = monoRight.getResolutionWidth() // 2, monoRight.getResolutionHeight() // 2
rrL.size.width, rrL.size.height = monoRight.getResolutionHeight(), monoRight.getResolutionWidth()
rrL.angle = -90
manipRight.initialConfig.setCropRotatedRect(rrL, False)
manipRight.inputConfig.setWaitForMessage(False)
monoRight.out.link(manipRight.inputImage)

monoLeft.out.link(stereo.left)
monoRight.out.link(stereo.right)

thanks
rex

**Comment by rexn8r** [comment]
hello

any thoughts on -90 degree rotation not working with 2.19??

thanks

**Comment by Erol444** [comment]
Hi @rexn8r ,
>  the Z value coming out wrong.

Could you provide screenshots that would showcase this, like `szabi` did in the comments?
Thanks, Erik

**Comment by rexn8r** [comment]
hello @Erol444 

please check following screenshots. the script is using depthai version 2.20.1.0

![IMG_20230203_113044](https://user-images.githubusercontent.com/12812556/216527114-7afd92b6-563e-4f01-8e71-e95db7c790ba.jpg)
![IMG_20230203_113106](https://user-images.githubusercontent.com/12812556/216527130-76deeba0-3b33-4333-9d58-b6e0aa44b477.jpg)
![IMG_20230203_113150](https://user-images.githubusercontent.com/12812556/216527131-21f308b4-8802-42ac-a9f4-86164272d927.jpg)

As you can see, the Z value comes out similar whether i am closer to the camera or far away.

thanks

**Comment by szabi-luxonis** [comment]
@rexn8r at the moment rotated frames are not supported, but we are planning to add support to latest depthai  version.
For now you need to use that specific depthai version for your use case.

**Comment by rexn8r** [comment]
Ok thanks
