### ISSUE TITLE
Gen2 License Plate Detection and OCR

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-experiments#47]
## Start with the `why`:

Now that we have the general text-detection + optical character recognition pipeline working ([here](https://github.com/luxonis/depthai-experiments#gen2-text-detection--optical-character-recognition-ocr-pipeline)), it would great to show a specific example of instead of doing overall text detection, to only detect license plates and then do OCR on them instead.

So below shows running the general OCR example on license plates:
![image](https://user-images.githubusercontent.com/32992551/105882082-7ec3fe00-5fc2-11eb-9a68-d785352213f9.png)

With a license-plate detector as the first stage (instead of a general text detector), likely things like the `DVD 493` plate would be correctly detected as one string instead of 2, for example.  And other attributes (like country, state, etc.) could be pulled off, as in our manual/hard-coded example of such a pipeline, [here](https://youtu.be/aID571OzBws).

## Move to the `how`:

Use the `vehicle-license-plate-detection-barrier-0106` detector instead of the `EAST` general text detector as the first-stage detector (and likely return additional metadata it may provide) and feed this into the OCR. 

An example of running this first-stage model is below:
![image](https://user-images.githubusercontent.com/32992551/105882474-e8440c80-5fc2-11eb-95e9-7e7296921d64.png)

And then in addition to this model as the first-stage, we should likely use `vehicle-attributes-recognition-barrier-0039` to get vehicle attributes and `license-plate-recognition-barrier-0001` to actually do the OCR of the plate (as in the hard-coded example, [here](https://youtu.be/aID571OzBws)).

## Move to the `what`:

Make a Gen2 pipeline example/reference application specific for license plate detection and optical character recognition (OCR).

**Comment by wasauce** [comment]
@Luxonis-Brandon in the video you linked https://youtu.be/aID571OzBws -- do you have the python code that was leveraging `license-plate-recognition-barrier-0001` such that you were getting OUT the text and then adding that label?

**Comment by Luxonis-Brandon** [comment]
We don't yet sorry @wasauce .  That video was the result of a static pipeline we made in C++ that we can't share unfortunately.  This pipeline was manually created on depthai in firmware in preparation for architecting the Gen2 pipeline builder.  So this is not possible, but we haven't yet implemented the pipeline in Gen2.  

I'm asking internally about availability to make this happen.  We had intended to make it already but have been behind.

**Comment by Luxonis-Brandon** [comment]
As an update @wasauce we think we'll have this Python example next week.  We got swamped doing the Gen2 release/docs (and are still behind on the docs), but should have some time to crank a first version out likely by the end of next week.

**Comment by wasauce** [comment]
@Luxonis-Brandon - Awesome. Thank you. I have started a PR here https://github.com/luxonis/depthai-experiments/pull/92/files. Many things to improve there and of course you can ignore it as you probably have a better approach, and depending on my free time this weekend -- you are likely to finish before me if you are targeting end of next week.

**Comment by Luxonis-Brandon** [comment]
Fantastic thank you @wasauce !  Will be good to compare notes I think!

**Comment by Luxonis-Brandon** [comment]
In progress here: https://github.com/luxonis/depthai-experiments/pull/94

And ArduCam made their own example, here: https://github.com/OAKChina/depthai-examples/tree/master/security_barrier_camera

**Comment by dhruvsheth-ai** [comment]
Surprisingly, their results seem to be really good

**Comment by Luxonis-Brandon** [comment]
Thanks CC: @VanDavv on ArduCam implementation.

**Comment by Luxonis-Brandon** [comment]
Initially implemented here: https://github.com/luxonis/depthai-experiments/tree/master/gen2-license-plate-recognition
