### ISSUE TITLE
Stream images on Windows

### ISSUE THREAD

**Issue by martin0496** [luxonis/depthai-experiments#471]
Hi all, 

I'm running the following code:
https://github.com/luxonis/depthai-experiments/tree/master/gen2-mjpeg-streaming

after running main.py, if i run http://localhost:8070/ in chrome i can see the class and confidence score but when i run http://localhost:8090/ the code crushes and stops. I receive the following message:
 127.0.0.1 - - [05/Apr/2023 12:09:49] "GET / HTTP/1.1" 200 -

What is the cause of this problem and how i can solve it to make it run on windows ?

**Comment by Erol444** [comment]
Can confirm this issue (working on Windows as well). I changed the demo to use opencv imencode instead, seems to work now. Perhaps this is less efficient way though, haven't tested it.

**Comment by Erol444** [comment]
@martin0496 please let us know if the PR fixes the issue on your end as well.
