### ISSUE TITLE
[gen2-yolo/device-decoding] Visualization doesn't show camera footage or detections

### ISSUE THREAD

**Issue by stwerner97** [luxonis/depthai-experiments#493]
Hi, I've tried the [gen2-yolo/device-decoding demo](https://github.com/luxonis/depthai-experiments/tree/master/gen2-yolo/device-decoding) but couldn't get the demo to work properly. Running ``python main.py --config model/yolov6ntrained.json`` opens a window that show neither the camera's images nor the detections of the yolov6 model.

The ``NN Results`` window simply shows the contents of the terminal in the background.

![image](https://github.com/luxonis/depthai-experiments/assets/36734964/05dee4c3-fc5c-4c69-a377-40b5e69968a2)

I have an **OAK-D CM4 PoE** and have followed the steps outlined in this [depthai-colab](https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/YoloV6_training.ipynb#scrollTo=91Z_AtMyvrId) to compile the ``.blob`` and ``.json`` that are placed in the ``model`` folder. I am using ``depthai==2.22.0.0`` and ``depthai-sdk==1.12.1``.

**Comment by Erol444** [comment]
Hi @stwerner97 ,
Which host computer are you using? Perhaps you could try using a different one? My guess is that X11 forwarding doesn't work as expected in your case.

**Comment by stwerner97** [comment]
Hi @Erol444, thanks for the response! 😊 

I am using a windows based machine. The X11 forwarding worked for me in another application (i.e., the depthai demo) - is there any difference between both applications in terms of the forwarding?

At the moment, I cannot check with a different machine, unfortunately.
