### ISSUE TITLE
To add mesh generation for gen2-pointcloud and Multiple camera

### ISSUE THREAD

**Issue by SahilJain8** [luxonis/depthai-experiments#497]
I am interested in making a pr for mesh generation using tsdf for gen2-pointcloud and multiple camera

**Comment by Erol444** [comment]
Hi @SahilJain8 ,
Feel free to create a PR, we will review it and merge it if it works as expected.
Thanks, Erik

**Comment by SahilJain8** [comment]
Thank You i will soon update it
