### ISSUE TITLE
Why pylance is complaining about NNData(), node, and ImageManipConfig() call in script.py from gen2-gaze-estimation project?(Solved)

### ISSUE THREAD

**Issue by rhsaeedy** [luxonis/depthai-experiments#506]
I am working with gen2-gaze-estimation and running the repo in vscode. But pylance is complaining about all instances of `NNData()`, `node`,  and `ImageManipConfig()` in the `script.py` file. I wonder what's the reason and how can I resolve it? I still can run the code somehow but those errors are somehow annoying.

**Comment by Erol444** [comment]
Hi @rhsaeedy ,
It's because the script.py isn't actually being executed on the host computer - it's being transferred to the OAK device, which auto-includes some libraries and adds some functionality. You can also rename the script.py to script.txt or something, so it won't try to do linting.

**Comment by rhsaeedy** [comment]
Thank you @Erol444.
