### ISSUE TITLE
Support for YOLOP

### ISSUE THREAD

**Issue by Bumbleboss** [luxonis/depthai-experiments#515]
Is it possible to support the use of YOLOP directly with OAKD?
https://github.com/hustvl/YOLOP

They have `.onnx` already available at their `/weights` directory.

**Comment by Erol444** [comment]
Hi @Bumbleboss ,
It can! We have a demo app with YOLOP here: https://github.com/luxonis/depthai-experiments/tree/master/gen2-yolo/yolop
