### ISSUE TITLE
Yolo v8 on OAK-D camera 

### ISSUE THREAD

**Issue by oussamaelmouiah** [luxonis/depthai-experiments#522]
I'm trying to run yolo model on OAK-D camera, so i created a "YoloSpatialNetworkDetection" node, to detect objects  and calculate theirs coordinates in the space, the issue is when i execute the code, it runs for just one second and then it crash.

you gonna find a copy of the code attached with the poste

thank you

![Capture d’écran du 2024-05-09 23-27-01](https://github.com/luxonis/depthai-experiments/assets/169404051/ea7e8772-8edc-404e-bdca-9b3291a9bad7
[Projet_OAK.zip](https://github.com/luxonis/depthai-experiments/files/15267949/Projet_OAK.zip)

**Comment by jakaskerl** [comment]
Solved https://discuss.luxonis.com/d/4704-yolospatialdetectionnetwork
