### ISSUE TITLE
Gaze Estimation termination issue

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai-experiments#54]
When [introduced a parallel implementation of Gaze Estimation example](https://github.com/luxonis/depthai-experiments/pull/51), we started to see the issues with thread termination, leading to unexpected console errors or even crash dialogs to appear.

## Examples:

---

```
File "main.py", line 312, in
Main().run()
File "main.py", line 302, in run
if cv2.waitKey(1) == ord('q'):
KeyboardInterrupt
Assertion failed: (pthread_mutexAssertion failed: (pthread_mutex_destroy(mutex) == 0), function _lock(mutex) == 0), function usbusbi_mutex_destroy, file ./os/thi_mutex_lock, file ./os/threads_reads_posix.h, line 58.
posix.h, line 46.
zsh: abort python3 main.py -cam
```

... FYI when I use the 'q' to exit the application. My quick suggestion is to properly join the threads and exit them when user pressed 'q' or ctrl+c.

---

```
python3: io.c:2115: handle_events: Assertion `ctx->pollfds_cnt >= internal_nfds' failed.
Aborted (core dumped)
```

---

![image](https://user-images.githubusercontent.com/1720147/106316554-cc8a7180-6221-11eb-9871-cd73a5ffbae1.png)

---

When the time permits, we should investigate these error messages and handle them properly, as it can also affect other examples

**Comment by Luxonis-Brandon** [comment]
Update from the investigation into this:
>Initial tests show that the abort issue doesn't pop up when using libusb 1.0.23 vs the latest 1.0.24
I presume that XLink (or our usage of it) doesn't use libusb correctly and it gets into a state where an assert fails.
Also it might be that this assert was added from 1.0.23 -> 1.0.24 - which shows this incorrect state. Will check this now

**Comment by raymondlo84** [comment]
Wow! Nice... =D! <3 Love you guys going deep into it so quickly! I cannot fix it unfortunately unless I have your brain :P

**Comment by VanDavv** [comment]
@raymondlo84 together with @themarpe we were able to solve this issue, more info here - https://github.com/luxonis/depthai-experiments/pull/57

**Comment by VanDavv** [comment]
It appears that I closed it automatically when I merged the PR. @raymondlo84 if it happens not to be resolved, please feel free to reopen

**Comment by raymondlo84** [comment]
FPS: 29.99
Assertion failed: (pthread_mutexAssertion failed: (pthread_mutex_destroy(mutex) == 0), function _lock(mutex) == 0), function usbusbi_mutex_destroy, file ./os/thi_mutex_lock, file ./os/threads_reads_posix.h, line 58.
posix.h, line 46.
zsh: abort      python main.py -cam 

I got it on the Mac today still.

**Comment by themarpe** [comment]
@raymondlo84 fix for this is underway to library - will let you know once ready:)
