### ISSUE TITLE
Not able to capture focused/clear iages with arducam imx283 

### ISSUE THREAD

**Issue by autonomy-123** [luxonis/depthai-experiments#549]
Hi @Erol444 ,

After the setup issue, I am stuck with another one.

When I run **main.py** script (under gen2-color-isp-raw) to test & capture images with **arducam imx283.**
Even tried increasing/decreasing autofocus with **','**  & **'.'** keypress but not able to capture.

Why is this so?
Is there any simpler way to set autofocus?

I am working Jetson device

**Comment by autonomy-123** [comment]
> Hi @Erol444 ,
> 
> After the setup issue, I am stuck with another one.
> 
> When I run **main.py** script (under gen2-color-isp-raw) to test & capture images with **arducam imx283.** Even tried increasing/decreasing autofocus with **','** & **'.'** keypress but not able to capture.
> 
> Why is this so? Is there any simpler way to set autofocus?
> 
> I am working Jetson device

**Comment by Erol444** [comment]
Hi @autonomy-123 ,
It's a manual focus camera, not auto-focus camera:
![image](https://github.com/user-attachments/assets/6e177a40-7bad-43b6-91a3-ac18cea84a75)

**Comment by autonomy-123** [comment]
> Hi @autonomy-123 , It's a manual focus camera, not auto-focus camera: ![image](https://private-user-images.githubusercontent.com/18037362/384405666-6e177a40-7bad-43b6-91a3-ac18cea84a75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzE4NDUsIm5iZiI6MTczMTEzMTU0NSwicGF0aCI6Ii8xODAzNzM2Mi8zODQ0MDU2NjYtNmUxNzdhNDAtN2JhZC00M2I2LTkxYTMtYWMxOGNlYTg0YTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA1NTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Zjg2Mjc2YjIxNzk1MTlhN2NmYjkzMTE4NTAyZWE3N2I1YTk0MTY2YjAxMzQ2ZjY1NDdmZDdiZTgxNjA4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U-voiIbQidcTkiZDZQJ1AzEw2fXTI8QwQ_stePv_ZmA)

@Erol444  yes I also checked it, yup it's working now.
But i wonder why in the main.py file they have written code for autofocus?.

**Comment by Erol444** [comment]
Because this script wasn't designed only for imx283 cam module - but for any cam module, which may or may not have AF

**Comment by autonomy-123** [comment]
> Because this script wasn't designed only for imx283 cam module - but for any cam module, which may or may not have AF

Okay @Erol444 thanks for clarification & ur support

**Comment by Erol444** [comment]
Happy to help!
