### ISSUE TITLE
TensorFlow example - resolve incorrect flower labelling

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai-experiments#55]
With the [TensorFlow Image Classification example added](https://github.com/luxonis/depthai-experiments/pull/53), we noticed that even though the example works correctly and outputs results as in [TF reference](https://www.tensorflow.org/tutorials/images/classification), the detected flower is not correct.

We should take a deeper look at the conversion steps [in this notebook](https://github.com/luxonis/depthai-experiments/pull/53), to verify if they are the issue here

**Comment by VanDavv** [comment]
I was thinking of adding a capability to send the images one by one and present them to the users - will also showcase how to use images instead of videos to interact with DepthAI

**Comment by raymondlo84** [comment]
=) Any suggestions on the blob converting step? Would it be related to I'm using 2021.2? And what are the easiest way to validate the blob?

**Comment by Luxonis-Brandon** [comment]
Great question.  @realWadim could you investigate what is going wrong here?

**Comment by raymondlo84** [comment]
=) Any updates? I think we will turn this into a tutorial once it is working. Also, would love to try classifying something different for fun too.

**Comment by Luxonis-Brandon** [comment]
Sorry about the delay.  Actually I had forgotten I assigned this to Wadim, who is no longer with Luxonis.  I'm going to see if Erik can help debug this.

Thanks,
Brandon

**Comment by raymondlo84** [comment]
=) Erik? Ok, would be great to know any sort of feedback. I am gonna ping a few and see if someone get enough insight into that. I am still guessing it has to do with the myriad compile step, and I don't have enough technical understanding of the entire pipeline there.

**Comment by raymondlo84** [comment]
I found the issue thanks to Szabi from Discord. 

Apparently, we have to add these two lines or the color information won't match with the OpenVINO format.

```
cam_rgb.setBoardSocket(dai.CameraBoardSocket.RGB)
cam_rgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
```

Then, I have to reverse the color again 
```
frame_rgb = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
# if the frame is available, draw bounding boxes on it and show the frame
if result is not None:
   cv2.putText(frame_rgb, "{} ({}%)".format(result["name"], result["conf"]), (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0))
```

https://colab.research.google.com/drive/1oNxfvx5jOfcmk1Nx0qavjLN8KtWcLRn6?usp=sharing

Also, I have made a validation script here and so you can see the IR format is working correctly. I think that is a very important step as we have to validate our input format (this is a deadly trap as nothing will work unless these are all pair-matched perfectly).

Please re-run this COLAB and download the new blob. And then perhaps make these updates.

**Comment by Luxonis-Brandon** [comment]
Awesome, thank you!  And sorry about the delay on this!  And thanks for tracking it down!

**Comment by VanDavv** [comment]
![ezgif com-gif-maker (25)](https://user-images.githubusercontent.com/5244214/109003919-522a0180-76a8-11eb-948c-a74432c22be1.gif)

The inference works ok now (although dandelion is only recognized in the mature form, but it's still better than before), 
PR with related changes is [here](https://github.com/luxonis/depthai-experiments/pull/72)

**Comment by raymondlo84** [comment]
Just tested it today and seems to be working as expected. I think this is sufficient to be a 'demo' now. It has all the puzzle together. =) 

-ray

**Comment by Luxonis-Brandon** [comment]
Thanks @raymondlo84 and also thanks for continuing to push on this and get it resolved!  Super appreciated!
