### ISSUE TITLE
Gen2 OCR Demo

### ISSUE THREAD

**Issue by dhruvsheth-ai** [luxonis/depthai-experiments#75]
[Error] Reported while running Gen2 OCR example on armv7l;
Using libraries -
numpy==1.19.5
opencv-python==4.5.1.48
depthai==0.0.2.1+e88c98c8a7681dd16cd754a832df1165380ac305

Error -
```bash
(venv2) pi@raspberrypi:~/depthai-experiments/gen2-ocr $ python3 main.py 
main.py:15: DeprecationWarning: setCamId() is deprecated, use setBoardSocket() instead.
  colorCam.setCamId(0)
terminate called without an active exception
Aborted
```

**Comment by Luxonis-Brandon** [comment]
Thanks for the report!

**Comment by alex-luxonis** [comment]
I think the depthai version there is missing this fix: https://github.com/luxonis/depthai-python/commit/87247bfb645027a30c68191d88fe1b69b70e39ac

We'll need to update the demo to use the latest version.
