### ISSUE TITLE
Missing attribute when running collecting-training-data.py

### ISSUE THREAD

**Issue by GlowingHorse** [luxonis/depthai-experiments#79]
My depthai version is 2.0.0.1

When I try to run the collecting data code, I find there are some AttributeError.
For example, 'depthai.Device' object has no attribute 'create_pipeline'

Are the codes in depthai-experiments incompatible with a new version of depthai?
Or is there a plan to reimplement them using a new version depthai?
Thanks.

**Comment by alex-luxonis** [comment]
There are some old apps using the Gen1 API, like this one.

You can find and install the specific depthai version that was used to test the app from the requirements.txt file. In this case:
https://github.com/luxonis/depthai-experiments/blob/master/collecting-training-data/requirements.txt

Now we switched to the Gen2 API, that was recently released, and the 2.0.0.1 version you have is the latest at the moment.
You can usually find Gen2 apps here in `depthai-experiments` in directories starting with `gen2-`.

**Comment by GlowingHorse** [comment]
Thanks! I will try it.
