### ISSUE TITLE
gen2-age-gender - RuntimeError: No available devices while using video as input

### ISSUE THREAD

**Issue by revelly** [luxonis/depthai-experiments#80]
This is in reference to experiment - gen2-age-gender 
Showing below message when using command 
>>python main.py -vid ./input.mp4
RuntimeError: No available devices

Note; I have not attached any camera device to system

**Comment by alex-luxonis** [comment]
A Luxonis device needs to be connected to the system. Even though the demo won't use the on-board camera, the video frames need to be sent from host over USB, then the device performs neural inference using the specialized AI processor, and sends the results back.

**Comment by rrdsml** [comment]
Thanks for quick response, got it! any possibility that we can use os instance processor (maybe with openVINO)?

**Comment by revelly** [comment]
Thanks for quick response, got it! any possibility that we can use os instance processor (maybe with openVINO)?

**Comment by alex-luxonis** [comment]
Not possible to use the DepthAI library with the host CPU as target processor.

But yes, you can use the same NN model with OpenVINO:
https://docs.openvinotoolkit.org/latest/omz_models_intel_age_gender_recognition_retail_0013_description_age_gender_recognition_retail_0013.html

You can find here a list of OpenVINO demos, together with their supported targets (CPU, GPU, or MYRIAD). The Luxonis devices are based on the MYRIAD architecture.
https://docs.openvinotoolkit.org/latest/omz_demos_README.html

**Comment by revelly** [comment]
ok. Thanks for the details!
