### ISSUE TITLE
Investigations on Gen2 WLS Filter Example Disparity Color Range Jumpiness

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-experiments#86]
In relation to https://github.com/luxonis/depthai-experiments/tree/master/gen2-wls-filter

The disparity color range is jumpy.  I don't know if this is out of my ignorance of how WLS works, or if it's something like the following. 

Below is a video showing it:
[https://youtu.be/IEqg0R2xA3g](https://youtu.be/IEqg0R2xA3g)

With that said, I'm guessing the color range is normalized every frame to the present min and max disparities, or something like that. So perhaps we could do a fixed normalization or some average over time as the scene changes maybe.

**Comment by alex-luxonis** [comment]
I think that instead of doing normalization, we should just extend the disparity range (e.g 0..95) to cover the pixel range (0..255), as here:
https://github.com/luxonis/depthai-experiments/blob/faa065e/gen2-camera-demo/main.py#L215

**Comment by Luxonis-Brandon** [comment]
Yes, good call!  Agreed. (And I should have thought of that.)

**Comment by szabi-luxonis** [comment]
Actually I should have thought about this :D
Should be fixed in : https://github.com/luxonis/depthai-experiments/pull/88

**Comment by Luxonis-Brandon** [comment]
Heh, thanks Szabi! :-)
