### ISSUE TITLE
Recompiling a network for better performance

### ISSUE THREAD

**Issue by AndrewBarfield** [luxonis/depthai-experiments#89]
For every example in this repo, I get the following warning (or something similar):

`
[14442C10A1E2F0D000] [22.544] [NeuralNetwork(2)] [warning] Network compiled for 13 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
`

I've looked but I find nothing about how to recompile for the '6 shaves' suggested.
Maybe I'm overthinking it?

[A Google search isn't helpful ...unless you want to learn about facial hair.](https://www.google.com/search?newwindow=1&sxsrf=ALeKk03iifoFoZqbv9QAt-IGE_X7FbtBXQ%3A1615426112871&ei=QHJJYN3VNMixggf047HIAg&q=%5Bwarning%5D+Network+compiled+for+13+shaves%2C+maximum+available+13%2C+compiling+for+6+shaves+likely+will+yield+in+better+performance&oq=%5Bwarning%5D+Network+compiled+for+13+shaves%2C+maximum+available+13%2C+compiling+for+6+shaves+likely+will+yield+in+better+performance&gs_lcp=Cgdnd3Mtd2l6EANQyIEBWMiBAWCHhQFoAHAAeACAAQCIAQCSAQCYAQGgAQGqAQdnd3Mtd2l6wAEB&sclient=gws-wiz&ved=0ahUKEwjd9fici6fvAhXImOAKHfRxDCkQ4dUDCA4&uact=5) 

Many thanks in advance!

**Comment by dhruvsheth-ai** [comment]
The SHAVES are vector processors in DepthAI. 
- For 1080p, 13 SHAVES (of 16) are free for neural network stuff.
- For 4K sensor resolution, 10 SHAVES are available for neural operations.

Usually for compute extensive models like pose estimation, OCR, facial landmarks etc, 13 SHAVES are required. However, the terminal will showcase an output recommendation for 6 SHAVES (usually). So this isn't an issue required to bother about. However if you wish to compile models with an alternative number of SHAVES, you can follow this -

https://docs.luxonis.com/projects/api/en/latest/tutorials/local_convert_openvino/

At the end, compile it with required SHAVES in the argument `-VPU_NUMBER_OF_SHAVES <enter the number of shaves>`
```bash
$MYRIAD_COMPILE -m ~/open_model_zoo_downloads/intel/face-detection-retail-0004/FP16/face-detection-retail-0004.xml -ip U8 -VPU_MYRIAD_PLATFORM VPU_MYRIAD_2480 -VPU_NUMBER_OF_SHAVES 4 -VPU_NUMBER_OF_CMX_SLICES 4
```

Or if you are using the Gen1 API, you could run the detection with the additional arguments, `sh` and `cmx` which use the required number of shaves -
`./depthai_demo.py -nce 2 -sh 14 -cmx 14`

Let me know if this helps, Thanks

**Comment by AndrewBarfield** [comment]
Thank you! This resolves my issue. I'll close it.
