### ISSUE TITLE
Update required for two-stage-inference

### ISSUE THREAD

**Issue by dhruvsheth-ai** [luxonis/depthai-experiments#93]
The module https://github.com/luxonis/depthai-experiments/tree/master/two-stage-inference has been using the depthai version `depthai==0.3.0.0+aeda4a9fdef6edc9f826b7dc354a123d1611a7c6`

This can be changed to depthai==2.0.0.1, to make it uniform with other modules.

Future update - Can be integrated to use `facial-landmarks-35-adas-0002.blob` instead of `landmarks-regression-retail-0009`

**Comment by Luxonis-Brandon** [comment]
Yes, would be great to get this updated to Gen2 to show a more basic two-stage inference example.

**Comment by VanDavv** [comment]
@dhruvsheth-ai the `two-stage-inference` example is using Gen1 API, and we have the same example written in Gen2 [here](https://github.com/luxonis/depthai-experiments/tree/master/gen2-nn-sync).
I noticed that it's not updated to `2.0.0.1` version though, so I made sure that this and other examples are using same version in [this PR](https://github.com/luxonis/depthai-experiments/pull/96)

**Comment by dhruvsheth-ai** [comment]
Thanks for the update!
