### ISSUE TITLE
Demo UI link in Readme broken

### ISSUE THREAD

**Issue by dhruvsheth-ai** [luxonis/depthai-experiments#95]
> Demo-UI (here)
Application used to demonstrate various capabilities of the DepthAI platform. Contains examples with descriptions, console outputs and preview windows.

This part in readme contains a link below. It redirects to 404, so needs a fix or removal

**Comment by Luxonis-Brandon** [comment]
Thanks.  @cafemoloko could you coordinate either fixing or removing?

**Comment by cafemoloko** [comment]
@Luxonis-Brandon - broken link fixed. Thank you @dhruvsheth-ai for the feedback!
